/** Generated by scripts/media/assemble-hero.ts. Do not edit by hand. */

/**
 * What the last assembly actually produced.
 *
 * The homepage reads this instead of probing the files at build time, so
 * the answer does not depend on ffmpeg being installed wherever the site
 * happens to be built. Widest rung first; HeroFilm picks between them.
 */
export const heroFilm = {
  durationSeconds: 13.76,
  rungs: ['hero-film-1920.mp4', 'hero-film-1280.mp4'] as const,
} as const;
