/** Generated by scripts/media/process.ts. Do not edit by hand. */
export interface MediaAsset {
  widths: number[];
  blurDataURL: string;
  width: number;
  height: number;
  aspectRatio: string;
}

export const media: Record<string, MediaAsset> = {
  'hero-poster': {
    widths: [640, 960, 1280, 1920],
    blurDataURL:
      'data:image/webp;base64,UklGRkwAAABXRUJQVlA4IEAAAADQAwCdASoUAAsAPxl0sVCspqSisAgBkCMJZwDLLCHcb5GuoQL1gAAA9940bP3uz2tF/okWjMoDlaoVCU6BAAAA',
    width: 1920,
    height: 1080,
    aspectRatio: '1920 / 1080',
  },
  'hero-still': {
    widths: [640, 960, 1280, 1920, 2560],
    blurDataURL:
      'data:image/webp;base64,UklGRlAAAABXRUJQVlA4IEQAAADQAwCdASoUAAsAPxl4tlGspyUisAgBkCMJYwAAUqUhOKuP5F3s8AAA/uy8wGs/mSTzX/j/83IJF+swHUOCgRg3qYAAAA==',
    width: 2752,
    height: 1536,
    aspectRatio: '2752 / 1536',
  },
  'pillar-corporate-finance': {
    widths: [640, 960, 1280, 1920],
    blurDataURL:
      'data:image/webp;base64,UklGRlIAAABXRUJQVlA4IEYAAACQAwCdASoUAA0APxl4slCspySisAgBkCMJZQAARkxJUaCK/+ggAP7gbmErnbK1C3Ki0pNQRj3/Hl4t7LbRB316R63gAAAA',
    width: 2528,
    height: 1696,
    aspectRatio: '2528 / 1696',
  },
  'pillar-ma': {
    widths: [640, 960, 1280, 1920],
    blurDataURL:
      'data:image/webp;base64,UklGRkwAAABXRUJQVlA4IEAAAABwAwCdASoUAA0APxl2slEspySisAgBkCMJYwAAQc0cq5D/oAAA/uv+nxoMejRUUteuXF9Pw8fedu+yf1JLgAAA',
    width: 2528,
    height: 1696,
    aspectRatio: '2528 / 1696',
  },
  'pillar-strategy': {
    widths: [640, 960, 1280, 1920],
    blurDataURL:
      'data:image/webp;base64,UklGRloAAABXRUJQVlA4IE4AAADwAwCdASoUAA0APxl4slEspySisAgBkCMJYwCw7BjtFZWMRubQrRMAAP7jWiXDh3OFy9gXepZzh+AXQBbuM92+XQwXsHciQ8xFUZgAAAA=',
    width: 2528,
    height: 1696,
    aspectRatio: '2528 / 1696',
  },
  'pillar-risk': {
    widths: [640, 960, 1280, 1920],
    blurDataURL:
      'data:image/webp;base64,UklGRk4AAABXRUJQVlA4IEIAAADQAwCdASoUAA0APxl0sVCspqSisAgBkCMJZQCdABi+InNySxJkwAAAzAI9ZXUwKXOtYfxnRWsFcum+uEo9x2q6GgA=',
    width: 2528,
    height: 1696,
    aspectRatio: '2528 / 1696',
  },
  'pillar-ai-digital': {
    widths: [640, 960, 1280, 1920],
    blurDataURL:
      'data:image/webp;base64,UklGRk4AAABXRUJQVlA4IEIAAACQAwCdASoUAA0APxl0sVCspqSisAgBkCMJZQAAQtq9zFL2xK8AAP7mXPlFldAPaQaH7oX/IS8k/KjM/yIs9uC2AAA=',
    width: 2528,
    height: 1696,
    aspectRatio: '2528 / 1696',
  },
  'about-1': {
    widths: [640, 960, 1280, 1920],
    blurDataURL:
      'data:image/webp;base64,UklGRkwAAABXRUJQVlA4IEAAAACwAwCdASoUAA0APxl6slCsqCSisAgBkCMJQBOgAw2lkvEWNy8ZEAD+6Ox8bczEWstb13B7a+H0+yEN6olXhgAA',
    width: 2528,
    height: 1696,
    aspectRatio: '2528 / 1696',
  },
  'about-2': {
    widths: [640, 960, 1280, 1920],
    blurDataURL:
      'data:image/webp;base64,UklGRlIAAABXRUJQVlA4IEYAAACwAwCdASoUAA0APxl2slCspySisAgBkCMJQBWAA6fPqoPQMljuAAD+409DbleaeNuxi1rlLkL9fFNCuJjKZuCBWZS8McAA',
    width: 2528,
    height: 1696,
    aspectRatio: '2528 / 1696',
  },
  contact: {
    widths: [960, 1280, 1920],
    blurDataURL:
      'data:image/webp;base64,UklGRlAAAABXRUJQVlA4IEQAAACQAwCdASoUAAsAPxl6tlIsp6UisAgBkCMJYwC7ACFSZIgd+rzAAP7uiDDv+mGV6+oU4lM9f+hL4e/m2o8Z3POW0NAAAA==',
    width: 2752,
    height: 1536,
    aspectRatio: '2752 / 1536',
  },
  'audience-companies': {
    widths: [640, 960, 1280],
    blurDataURL:
      'data:image/webp;base64,UklGRnIAAABXRUJQVlA4IGYAAAAQBQCdASoUABQAPxl4tFMspyUisBgIAZAjCWYAuzLHQTT4dLluBDL5S/ik8Qnh0ayQAP6Cf3pgoqPImOlmxg9P6sTj1Y5cKfSrTRtmvTvVeAYNMTH6MW8paQsDL7adGHMC1aG/YAA=',
    width: 2048,
    height: 2048,
    aspectRatio: '2048 / 2048',
  },
  'audience-funds': {
    widths: [640, 960, 1280],
    blurDataURL:
      'data:image/webp;base64,UklGRm4AAABXRUJQVlA4IGIAAACwBACdASoUABQAPxl4slEspySisAgBkCMJQBkTBBiDm1EiH/PA/L1I5G7dyl0QAP7TICthbAu184LsvPsRDbkkrZkT57Ydu1IaKzIx41yGZBzGkXcQWVV+5PcatISeW0AAAA==',
    width: 2048,
    height: 2048,
    aspectRatio: '2048 / 2048',
  },
  'audience-professionals': {
    widths: [640, 960, 1280],
    blurDataURL:
      'data:image/webp;base64,UklGRm4AAABXRUJQVlA4IGIAAADQBACdASoUABQAPxl2tlMspqUisBgIAZAjCWMAACWh8+FbNskDw8hiVnqPoChjgADMdp+1B7Z+5TYO8XbkUbvH2Rp7g3Dp9G+TyyW8pMrtMy/ZPZOh1+nO8RiEibUY/Ni8AA==',
    width: 2048,
    height: 2048,
    aspectRatio: '2048 / 2048',
  },
  statement: {
    widths: [640, 960, 1280],
    blurDataURL:
      'data:image/webp;base64,UklGRlgAAABXRUJQVlA4IEwAAAAQBACdASoUAA0APxl2s1CspySisAgBkCMJYwC7AB33WOiZRhcoODmrAAD+ZgqDWjUS8DCW0CK89JDay/Jw1LtO0SUzIA8CW3g9j4AA',
    width: 2528,
    height: 1696,
    aspectRatio: '2528 / 1696',
  },
  'insight-career': {
    widths: [640, 960, 1280],
    blurDataURL:
      'data:image/webp;base64,UklGRlIAAABXRUJQVlA4IEYAAACwAwCdASoUAAsAPxl2s1EspySisAgBkCMJZQC/OA+MqcLvmTAAAADfVCr0itHRk8CgJ51Ar6cDlcxXG2qEw41qoG6LrQAA',
    width: 2752,
    height: 1536,
    aspectRatio: '2752 / 1536',
  },
  'insight-commodities': {
    widths: [640, 960, 1280],
    blurDataURL:
      'data:image/webp;base64,UklGRlYAAABXRUJQVlA4IEoAAAAQBACdASoUAAsAPxl0sVCspqSisAgBkCMJYwDG9CIGa2/fBxSeaViWgAD8zMruhGLCuEoSeg4rlGXkFYX2ZDV6jNRm1KFwoA5gAA==',
    width: 2752,
    height: 1536,
    aspectRatio: '2752 / 1536',
  },
  'insight-purpose': {
    widths: [640, 960, 1280],
    blurDataURL:
      'data:image/webp;base64,UklGRlYAAABXRUJQVlA4IEoAAACwAwCdASoUAAsAPxl4s1EspySisAgBkCMJQBAAALgevkpaw3ZFoAD3HvKgldtvMYy9kFcY6gzftD8ycPgRbOODepWuXvn4Lx9gAA==',
    width: 2752,
    height: 1536,
    aspectRatio: '2752 / 1536',
  },
  'insight-identity': {
    widths: [640, 960, 1280],
    blurDataURL:
      'data:image/webp;base64,UklGRl4AAABXRUJQVlA4IFIAAAAwBACdASoUAAsAPxl2s1EspySisAgBkCMJYgCdAB9S4FUK8uU4Oot8ngAA/fadQtpz43axdf6aDKg74svIYieBnddWCMUfAGgw9HwHW1lrrqwA',
    width: 2752,
    height: 1536,
    aspectRatio: '2752 / 1536',
  },
  'network-1': {
    widths: [640, 960, 1280],
    blurDataURL:
      'data:image/webp;base64,UklGRooAAABXRUJQVlA4IH4AAACQBACdASoUABkAPxl6slCsqCSisAgBkCMJYwC2+2QDTqvV9+1Q54zLS3CPJkAA/eKaFTUCgCumQI7x7Pf7JrYuIqGQ2NMyLkRcxa8MInMRJQ0x5McuY0iINr51qplKR8laWQ6NWHh4JPHNdwHdWTbLiwS5rfOa/rePVZVAAAA=',
    width: 1856,
    height: 2304,
    aspectRatio: '1856 / 2304',
  },
  'network-2': {
    widths: [640, 960, 1280],
    blurDataURL:
      'data:image/webp;base64,UklGRnQAAABXRUJQVlA4IGgAAADQBACdASoUABkAPxl0slCspqSisBgMAZAjCUAW9wHhNfb3foOVtmZdPPQzWr+yAAD+1ZfcTFfO/JUPqO1/d/Vvll3XnVnOfPNLTKlK60Cd6yoYMCqOYS7AZvSIZW6BT1jxKbkPxuRiAA==',
    width: 1856,
    height: 2304,
    aspectRatio: '1856 / 2304',
  },
  'texture-01': {
    widths: [400, 800, 1200],
    blurDataURL:
      'data:image/webp;base64,UklGRlgAAABXRUJQVlA4IEwAAADQAwCdASoUABQAPxl2tlOspqUkMBgIAZAjCWcAwCgQ8KjGCp1LlQAA/q8+c78+VqsQqYgoWubpejcsctr+MTX/ENdgP4ypcUouqkAA',
    width: 2048,
    height: 2048,
    aspectRatio: '2048 / 2048',
  },
  'texture-02': {
    widths: [400, 800, 1200],
    blurDataURL:
      'data:image/webp;base64,UklGRlQAAABXRUJQVlA4IEgAAABwAwCdASoUABQAPxl8sVOsp6QiqA1RkCMJZ2rmWKIKjuhDxMAA/uqR7ycu/1GIC6vZIkj7hAcl0iu0L7xYxQM4DIsS8RwIAAA=',
    width: 2048,
    height: 2048,
    aspectRatio: '2048 / 2048',
  },
  'texture-03': {
    widths: [400, 800, 1200],
    blurDataURL:
      'data:image/webp;base64,UklGRmwAAABXRUJQVlA4IGAAAADQBACdASoUABQAPxl+slOsqCQiqA1RkCMJZQDImBEc9MwIGKCUw/vK+JF7MVtpmADOMs6wvwXF/GNUv8mum4q7V75C8fi0L49LY+xRemxYtd6iGTwGHUUd10pqUxfYAAA=',
    width: 2048,
    height: 2048,
    aspectRatio: '2048 / 2048',
  },
  'texture-04': {
    widths: [400, 800, 1200],
    blurDataURL:
      'data:image/webp;base64,UklGRlAAAABXRUJQVlA4IEQAAADQAwCdASoUABQAPw1yrlCsJyQit/VYAYAhiWcAz6APDMAkyLESwRAA/tlAMDWLMdTExy5KaThDk5BI87JfbtKDQ4AAAA==',
    width: 2048,
    height: 2048,
    aspectRatio: '2048 / 2048',
  },
  'texture-05': {
    widths: [400, 800, 1200],
    blurDataURL:
      'data:image/webp;base64,UklGRjwAAABXRUJQVlA4IDAAAAAQAwCdASoUABQAPxmEu1asqKYjqAgBkCMJZwCw7BdwNoAA/upyK3582ZRypgIy+AA=',
    width: 2048,
    height: 2048,
    aspectRatio: '2048 / 2048',
  },
  'texture-06': {
    widths: [400, 800, 1200],
    blurDataURL:
      'data:image/webp;base64,UklGRlYAAABXRUJQVlA4IEoAAADQAwCdASoUABQAPxl4tVGspyUiqA1RkCMJZwDDcAwvC459+xHdWSAA/uWYcVnWxYocUAij4ul714KaFWGMQAJr9K7v51Lg+LmAAA==',
    width: 2048,
    height: 2048,
    aspectRatio: '2048 / 2048',
  },
};
