/**
 * The people register. Every field traces to content/_source/people.md, except the
 * three homepage-only entries at the end, which trace to content/_source/home.md.
 *
 * Biographies are cleaned drafts for partner review: typos, doubled words and US
 * spellings fixed, no fact, figure, employer, qualification or date changed.
 */
import { z } from 'zod';
import { Person } from './schema';

const data = [
  // ---------------------------------------------------------------- managing partners
  {
    slug: 'keshav-adya',
    name: 'Keshav Adya',
    printedAs: 'Chennakeshav (Keshav) Adya',
    role: 'Managing Partner',
    group: 'managing-partner',
    city: 'Dubai',
    country: 'United Arab Emirates',
    timeZone: 'Asia/Dubai',
    email: 'ck.adya@adancorporate.com',
    linkedin: 'https://www.linkedin.com/in/cadya/',
    bio: "Keshav is the founding Managing Partner of Adan Corporate. He has 20+ years of international corporate and entrepreneurial experience across corporate finance advisory, international growth, M&A, technology delivery and fund-raising, for firms including Morgan Stanley, Lloyds Banking Group, HSBC, Marks and Spencer, Sainsbury's, IMS Health, TCS and Hitachi Rail, in 25+ countries. He is an Entrepreneur Mentor in Residence at London Business School, where he holds an MBA.",
    expertise: [
      'M&A',
      'Post-Merger Integration (PMI)',
      'Private Equity',
      'Startups - Growth Capital',
      'Commercial Negotiation',
      'NED & Board Advisory Services',
      'Deal Strategy',
      'Business Strategy',
      'Corporate Strategy',
      'Growth Strategy',
      'Marketing Strategy',
      'Career Transition',
      'Family Offices Investments',
      'Fund Placement',
      'Credit Ratings Assistance',
      'Special Situations',
      'Distressed Asset Management',
      'Asset Management',
      'Equity Financing',
      'Debt Financing',
      'Risk Management',
      'Blockchain',
      'Analytics',
      'Interim CEO / Managing Director',
      'Interim CMO',
    ],
    sectors: [
      'Technology',
      'Media & Entertainment',
      'Healthcare Systems & Services',
      'Pharma & Life Sciences',
      'Private Equity',
      'Retail',
      'Real Estate',
      'Banking & Capital Markets',
      'Advanced Electronics',
      'Green Energy',
      'Travel, Transport & Logistics',
    ],
    geographies: ['UK', 'India', 'USA', 'UAE', 'Asia Pacific', 'Australia'],
    pillars: ['corporate-finance', 'mergers-acquisitions', 'strategy-leadership'],
    portrait: '/media/people/keshav-adya.avif',
    needsPortrait: false,
    notes:
      'Second city: London (printed "DUBAI & LONDON"). His bio is the only source of the "45+ senior corporate professionals in 18 countries" figure, which the 29-person team page contradicts; the figure is not carried here. He is commented out of the homepage team grid yet is listed as the page author and bylined on two homepage insight cards: confirm his current status. Source expertise list repeated "Private Equity" and "Deal Strategy"; "Financial Services" and "Capital Projects & Infra" were listed as expertise and dropped as sector names.',
  },
  {
    slug: 'ajay-mavinkurve',
    name: 'Ajay Mavinkurve',
    role: 'Managing Partner',
    group: 'managing-partner',
    city: 'London',
    country: 'United Kingdom',
    timeZone: 'Europe/London',
    email: 'ajay.mavinkurve@adancorporate.com',
    linkedin: 'https://www.linkedin.com/in/ajay-mavinkurve',
    bio: 'Ajay is a corporate finance executive with 30+ years of experience in global corporate finance, IPOs, corporate and tax structuring, deal structuring, commercial negotiation, valuations, venture and private equity syndication, M&A and buy-outs for small and mid-sized enterprises. He ran his own financial services company in Mumbai for 17+ years from 1987, then led a global media firm to an AIM listing in London. In 2013 he repositioned Adan Corporate with a global outlook. He is a Chartered Accountant and holds an MBA from London Business School.',
    expertise: [
      'IPO',
      'Private Equity',
      'Project Finance',
      'Debt Financing',
      'Deal Strategy',
      'Commercial Negotiation',
      'Distressed Asset Management',
      'Transformation and Restructuring',
      'M&A',
      'Business Strategy',
      'NED & Board Advisory Services',
      'Working Capital and Trade Finance',
      'Startups - Growth Capital',
      'Credit Ratings Assistance',
      'Interim CFO',
    ],
    sectors: [
      'Media & Entertainment',
      'Banking & Capital Markets',
      'Private Equity',
      'Financial Services',
      'Technology',
      'Industrial Manufacturing',
      'Healthcare Systems & Services',
      'Pharma & Life Sciences',
      'Green Energy',
      'Real Estate',
      'Chemicals & Polymers',
    ],
    geographies: ['UK', 'India', 'USA', 'UAE', 'Asia Pacific'],
    pillars: ['corporate-finance', 'mergers-acquisitions', 'strategy-leadership'],
    portrait: '/media/people/ajay-mavinkurve.avif',
    needsPortrait: false,
    notes:
      'His sidebar taxonomy is reproduced byte-for-byte on two other profiles (Saba Suryanarayanan, Neeraj Arora); confirm which of the three it belongs to.',
  },
  {
    slug: 'sabapaty-suryanarayanan',
    name: 'Saba Suryanarayanan',
    printedAs: 'Sabapaty (Saba) Suryanarayanan',
    role: 'Managing Partner',
    group: 'managing-partner',
    city: 'Mumbai',
    country: 'India',
    timeZone: 'Asia/Kolkata',
    email: 'sabapatys@adancorporate.com',
    linkedin: 'https://www.linkedin.com/in/sabapaty-suryanarayanan-96a31b4',
    bio: 'Saba is a commercial and finance professional with 30+ years of experience across manufacturing, trading, media and financial services, in deal structuring, commercial negotiation, growth strategy, distressed asset management, working capital funding and buyouts. He has been CFO of a leading Indian entertainment company, general manager of an outsourcing unit for a UK company, and managing director of FMCG companies in Africa and of a trading company in Eastern Europe. He is a Chartered Accountant, based in Mumbai.',
    expertise: [
      'IPO',
      'Private Equity',
      'Project Finance',
      'Debt Financing',
      'Deal Strategy',
      'Commercial Negotiation',
      'Distressed Asset Management',
      'Transformation and Restructuring',
      'M&A',
      'Business Strategy',
      'NED & Board Advisory Services',
      'Working Capital and Trade Finance',
      'Startups - Growth Capital',
      'Credit Ratings Assistance',
      'Interim CFO',
    ],
    sectors: [
      'Industrial Manufacturing',
      'Retail',
      'Banking & Capital Markets',
      'Technology',
      'Media & Entertainment',
      'Financial Services',
      'Private Equity',
      'Pharma & Life Sciences',
      'Healthcare Systems & Services',
    ],
    geographies: ['India', 'Eastern Europe', 'Asia', 'Africa'],
    pillars: ['corporate-finance', 'mergers-acquisitions', 'strategy-leadership'],
    portrait: '/media/people/sabapaty-suryanarayanan.avif',
    needsPortrait: false,
    notes:
      'His expertise list is byte-identical to Ajay Mavinkurve\'s; confirm it is his own. The homepage version of his bio reads "experience in in C-suite roles" (doubled word) and adds a C-suite claim the profile page does not make; the profile wording is used here.',
  },

  // ------------------------------------------------------------------------- partners
  {
    slug: 'rauf-akhundov',
    name: 'Rauf Akhundov',
    role: 'Partner',
    roleDetail: 'Central Asia',
    group: 'partner',
    city: 'Baku',
    country: 'Azerbaijan',
    timeZone: 'Asia/Baku',
    email: 'r.akhundov@adancorporate.com',
    linkedin: 'https://www.linkedin.com/in/rauf-akhundov-89495022/',
    bio: "Rauf is a banker with 20+ years of international experience in fundraising, strategic planning and budgeting, consumer, micro and corporate lending, network management and relationship management with government officials in emerging markets. He was Deputy CEO and board member of DemirBank, Azerbaijan's leading private commercial bank, Vice President, Finance at Akkord, and country officer for Azerbaijan and Central Asia at the International Finance Corporation. He holds a Sloan Master's in Leadership and Strategy from London Business School.",
    expertise: [
      'Project Finance',
      'Private Equity',
      'Equity Financing',
      'Debt Financing',
      'Working Capital and Trade Finance',
      'Transformation and Restructuring',
      'Commercial Negotiation',
    ],
    sectors: [
      'Banking & Capital Markets',
      'Financial Services',
      'Public Sector',
      'Government & Public Services',
      'Sovereign Investment Funds',
    ],
    geographies: ['Azerbaijan', 'Central Asia'],
    pillars: ['corporate-finance'],
    portrait: '/media/people/rauf-akhundov.avif',
    needsPortrait: false,
    notes:
      'Email format differs from the firm norm (r.akhundov@ rather than first.last@). He is commented out of the homepage team grid: confirm he is still with the firm.',
  },
  {
    slug: 'neeraj-arora',
    name: 'Neeraj Arora',
    role: 'Partner',
    group: 'partner',
    city: 'London',
    country: 'United Kingdom',
    timeZone: 'Europe/London',
    email: 'neeraj.arora@adancorporate.com',
    linkedin: 'https://www.linkedin.com/in/neeraj-arora-16537313/',
    bio: 'Neeraj specialises in media monetisation and storytelling, with over 30 years in the industry. He spent two decades at Sony Pictures, between 2004 and 2024, leading international business, and has launched and expanded media brands including Zee, B4U and Sony across more than 100 countries. He was named Media Icon of the Year 2024 at the High Flyer 50 Global Icon Awards and received a Lifetime Achievement Award in 2025 at the British Asian Media Awards. He is Founder and CEO of NNA Consultants Limited.',
    expertise: [],
    sectors: [
      'Media & Entertainment',
      'Banking & Capital Markets',
      'Private Equity',
      'Financial Services',
      'Technology',
      'Industrial Manufacturing',
      'Healthcare Systems & Services',
      'Pharma & Life Sciences',
      'Green Energy',
      'Real Estate',
      'Chemicals & Polymers',
    ],
    geographies: ['UK', 'India', 'USA', 'UAE', 'Asia Pacific'],
    pillars: ['strategy-leadership', 'ai-digital'],
    portrait: '/media/people/neeraj-arora.avif',
    needsPortrait: false,
    // Expertise is left empty on purpose: the source list is a template copy, not his.
    notes:
      'His expertise, sectors and geographies blocks are byte-identical to Ajay Mavinkurve\'s and describe corporate finance, not media. The expertise list (IPO, Project Finance, Interim CFO and so on) is withheld pending a replacement from him; sectors and geographies are carried but unconfirmed. His bio names his own firm, NNA Consultants Limited: confirm whether that should be surfaced. His profile says "Sony Pictures Entertainment" in one paragraph and "Sony Pictures Networks" in another. Headshot filename contains spaces and needs renaming on migration.',
  },
  {
    slug: 'sandeep-bhat',
    name: 'Sandeep Bhat',
    role: 'Partner',
    roleDetail: 'Capital market',
    group: 'partner',
    city: 'India',
    country: 'India',
    timeZone: 'Asia/Kolkata',
    email: 'sandeep.bhat@adancorporate.com',
    linkedin: 'https://www.linkedin.com/in/sandeep-bhat-59225378/',
    bio: 'Sandeep is a financial services professional with 30+ years in C-suite roles at global banks and private equity firms, covering accounting, financial control, treasury management, tax, operational risk control, legal and compliance. He was CFO at ABN AMRO, setting up its broking business in India, COO at CLSA India, Executive Director and COO, India at UBS, and a founding member of the team at Aditya Birla Private Equity. He is a Chartered Accountant and a CPA (Australia).',
    expertise: [
      'Technical Analysis',
      'Finance Control',
      'Treasury Management',
      'Risk Control',
      'Merchant Banking',
      'IPO',
      'Human Resource & Administration',
    ],
    sectors: [
      'Capital Markets',
      'Private Banking',
      'Private Equity',
      'Wealth Management',
      'Real Estate',
    ],
    geographies: ['India', 'Japan'],
    pillars: ['corporate-finance', 'risk-governance'],
    portrait: '/media/people/sandeep-bhat.avif',
    needsPortrait: false,
    notes:
      'City is printed only as "India" on both the profile and the homepage; his bio names Mumbai only in connection with an educational trust, so no city is asserted here. Confirm his base. Source sectors read "Real-Estate"; normalised. Headshot filenames (sandeep-main.png, sandeep-team.png) break the naming convention.',
  },
  {
    slug: 'george-christelis',
    name: 'George Christelis',
    role: 'Partner',
    roleDetail: 'Southern African region',
    group: 'partner',
    city: 'Johannesburg',
    country: 'South Africa',
    timeZone: 'Africa/Johannesburg',
    email: 'george.christelis@adancorporate.com',
    linkedin: 'https://www.linkedin.com/in/george-christelis-05753545/',
    bio: 'George is a finance professional with 20+ years of experience as CFO of listed medium and large businesses in real estate, construction, engineering and logistics. He has been CFO of PSV Holdings and Questek Holdings, finance director of Zotos Property Group and Hellmann Worldwide Logistics, and senior finance consultant to Texton Property Fund and Netcare 911. He is a Sloan Fellow of London Business School and a Chartered Accountant (SAICA).',
    expertise: [
      'Project Finance',
      'Debt Syndication',
      'Deal Strategy',
      'Commercial Negotiation',
      'Distressed Asset Management',
      'Transformation and Restructuring',
      'Business Strategy',
      'NED & Board Advisory Services',
      'Interim CFO',
      'Coaching & Mentoring',
      'Career Transition',
      'Company Valuation',
      'Corporate Strategy',
      'Board Advisors',
    ],
    sectors: [
      'Real Estate',
      'Semiconductors',
      'Engineering & Construction',
      'Technology',
      'Travel, Transport & Logistics',
    ],
    geographies: ['South Africa', 'UK'],
    pillars: ['corporate-finance', 'strategy-leadership'],
    portrait: '/media/people/george-christelis.avif',
    needsPortrait: false,
  },
  {
    slug: 'vernon-d-cruz',
    name: "Vernon D'Cruz",
    role: 'Partner',
    roleDetail: 'Commercial, tourism & CSR',
    group: 'partner',
    city: 'Mumbai',
    country: 'India',
    timeZone: 'Asia/Kolkata',
    email: 'vernon.dcruz@adancorporate.com',
    linkedin: 'https://www.linkedin.com/in/vernondcruz/',
    bio: 'Vernon is a finance professional with 30+ years of experience in mid-sized service organisations, with hands-on knowledge of finance, taxation, legal matters, commercial negotiation, tourism and CSR. He built a travel and tourism company from scratch and ran it for 20 years, and advises travel companies on growth and exit strategies. Earlier he headed finance operations at a fast-growing tour operator, sourcing funding for hotel projects and structuring a buy-out. He is a Chartered Accountant, based in Mumbai.',
    expertise: [
      'Commercial Negotiation',
      'Special Situations',
      'Distressed Asset Management',
      'Transformation and Restructuring',
      'Private Equity',
      'Project Finance',
      'Debt Syndication',
      'Deal Strategy',
      'M&A',
      'Business Strategy',
      'NED & Board Advisory Services',
      'Working Capital and Trade Finance',
      'Interim CFO',
    ],
    sectors: [
      'Travel, Transport & Logistics',
      'Insurance',
      'Social Sector',
      'Banking & Capital Markets',
      'Financial Services',
    ],
    geographies: ['India', 'South East Asia'],
    pillars: ['corporate-finance', 'mergers-acquisitions'],
    portrait: '/media/people/vernon-d-cruz.avif',
    needsPortrait: false,
    notes:
      'Source expertise list repeated "Special Situations"; deduplicated. Source bio read "mid-sizes service organisations" and repeated the phrase "Commercial Negotiations, Commercial, Tourism & CSR" twice; both corrected. The team-page image alt text prints his name without the apostrophe.',
  },
  {
    slug: 'edgar-garay',
    name: 'Edgar Garay',
    role: 'Partner',
    roleDetail: 'Corporate finance',
    group: 'partner',
    city: 'Bogota',
    country: 'Colombia',
    timeZone: 'America/Bogota',
    email: 'Edgar.Garay@adancorporate.com',
    linkedin: 'https://www.linkedin.com/in/garayedgar/',
    bio: 'Edgar has 30+ years of experience across diverse asset classes, industries and geographies. He specialises in helping mid-sized businesses structure and deploy an active-ownership approach that improves business strategies and operating structures, aligned to shareholder value. He has been CEO of Barracuda Finance, finance director of GEMS Education, corporate investment manager at Alesayi Group and vice president of asset management at Jones Lang LaSalle MENA. He holds an MBA from London Business School and a degree in industrial engineering from Pontificia Universidad Javeriana.',
    expertise: [
      'M&A',
      'Risk Management',
      'Private Equity',
      'Special Situations',
      'Transformation and Restructuring',
      'Corporate Finance',
      'Company Valuation',
      'Deal Strategy',
      'Business Strategy',
      'Corporate Strategy',
    ],
    sectors: [
      'Technology',
      'Private Equity',
      'Industrial Manufacturing',
      'Banking & Capital Markets',
      'Advanced Electronics',
      'Green Energy',
    ],
    geographies: [],
    pillars: ['corporate-finance', 'mergers-acquisitions', 'strategy-leadership'],
    portrait: '/media/people/edgar-garay.avif',
    needsPortrait: false,
    notes:
      'His expertise, sectors and geographies blocks are byte-identical to Roland Giebitz\'s. The source geographies read "Germany | Europe | USA", which contradicts a Bogota base and a bio covering MENA and Colombia, so they are withheld pending confirmation; sectors are carried but unconfirmed. "Financial Services" and "Capital Projects & Infra" were listed as expertise and dropped as sector names. Source bio read "GEMS eduction"; corrected. Email is mixed-case in the source mailto. He is commented out of the homepage team grid.',
  },
  {
    slug: 'roland-giebitz',
    name: 'Roland Giebitz',
    role: 'Partner',
    roleDetail: 'Corporate finance',
    group: 'partner',
    city: 'Hamburg',
    country: 'Germany',
    timeZone: 'Europe/Berlin',
    email: 'Roland.Giebitz@adancorporate.com',
    linkedin: 'https://www.linkedin.com/in/roland-giebitz-10292158',
    bio: 'Roland is an executive with 30+ years of experience managing companies and leading operational and business development projects. He has consulted with McKinsey, Strategic Decisions Group and Accelerate Business Consulting, and held management roles as managing director of Sartorius Separation Engineering, CFO of SUSE Linux AG and investment manager at venture capital firms. His recent focus is business planning and helping clients finance their projects. He holds an MBA from London Business School and a management degree from Goethe University, Frankfurt.',
    expertise: [
      'M&A',
      'Risk Management',
      'Private Equity',
      'Special Situations',
      'Transformation and Restructuring',
      'Corporate Finance',
      'Company Valuation',
      'Deal Strategy',
      'Business Strategy',
      'Corporate Strategy',
    ],
    sectors: [
      'Technology',
      'Private Equity',
      'Industrial Manufacturing',
      'Banking & Capital Markets',
      'Advanced Electronics',
      'Green Energy',
    ],
    geographies: ['Germany', 'Europe', 'USA'],
    pillars: ['corporate-finance', 'mergers-acquisitions', 'strategy-leadership'],
    portrait: '/media/people/roland-giebitz.avif',
    needsPortrait: false,
    notes:
      '"Financial Services" and "Capital Projects & Infra" were listed as expertise and dropped as sector names. His whole taxonomy block is duplicated on Edgar Garay\'s profile: confirm which it describes. Email is mixed-case in the source mailto.',
  },
  {
    slug: 'preethi-hari',
    name: 'Preethi Hari',
    role: 'Partner',
    roleDetail: 'Risk management',
    group: 'partner',
    city: 'London',
    country: 'United Kingdom',
    timeZone: 'Europe/London',
    email: 'preethi.hari@adancorporate.com',
    linkedin: 'https://www.linkedin.com/in/preethihari/',
    bio: 'Preethi is a governance, risk and compliance professional with 18+ years of experience in risk management, IT governance, IT security, business continuity, audit, compliance and regulation. She specialises in the COBIT and COSO frameworks, ITSM (ITIL), Six Sigma and SOX across banking, insurance, oil and gas, shipping, mining, logistics, telecoms and commercial real estate. She has led large risk and compliance programmes for Deloitte, Ernst & Young and KPMG, and holds an MBA from London Business School.',
    expertise: [
      'Risk Management',
      'Risk Strategy',
      'Enterprise Risk Management',
      'Target Due-Diligence',
      'Digital',
      'Business Strategy',
      'Corporate Strategy',
      'Transformation and Restructuring',
      'Interim CRO',
    ],
    sectors: [
      'Real Estate',
      'Banking & Capital Markets',
      'Mining',
      'Oil & Gas',
      'Travel, Transport & Logistics',
      'Shipping',
      'Insurance',
      'Capital Projects & Infra',
      'Financial Services',
    ],
    geographies: ['UK', 'India'],
    pillars: ['risk-governance', 'ai-digital'],
    portrait: '/media/people/preethi-hari.avif',
    needsPortrait: false,
    notes:
      'Her bio names Deutsche Bank, ING, Bank of America, Barclays and Lloyds as client-side employers; that client list is not published here pending confirmation. She is commented out of the homepage team grid.',
  },
  {
    slug: 'thu-nga-haskovcova',
    name: 'Thu Nga Haskovcova',
    role: 'Partner',
    roleDetail: 'Central Eastern Europe, law',
    group: 'partner',
    city: 'Prague',
    country: 'Czech Republic',
    timeZone: 'Europe/Prague',
    email: 'thu.nga@adancorporate.com',
    linkedin: 'https://www.linkedin.com/in/thu-nga-haskovcova-32431110/',
    bio: "Thu Nga is a Czech qualified lawyer with 20 years of international experience in M&A, market entry and start-ups, real estate, financing, private equity and corporate law. She has in-depth local knowledge of the Central Eastern European region and working experience in South East Asia. She holds an MBA from London Business School, a PhD in law from Charles University, Prague, and a master's in international law from Moscow State University of International Relations (MGIMO).",
    expertise: [
      'Project Finance',
      'Private Equity',
      'Equity Financing',
      'Debt Financing',
      'Working Capital and Trade Finance',
      'Transformation and Restructuring',
      'Commercial Negotiation',
    ],
    sectors: ['Banking & Capital Markets', 'Financial Services', 'Real Estate'],
    geographies: ['Eastern Europe', 'South East Asia'],
    pillars: ['corporate-finance', 'mergers-acquisitions'],
    portrait: '/media/people/thu-nga-haskovcova.avif',
    needsPortrait: false,
    notes: 'Source geography read "Sout East Asia"; corrected.',
  },
  {
    slug: 'vinayak-hattangadi',
    name: 'Vinayak Hattangadi',
    role: 'Partner',
    roleDetail: 'Executive director & interim CTO',
    group: 'partner',
    city: 'Mumbai',
    country: 'India',
    timeZone: 'Asia/Kolkata',
    email: 'vinayak.hattangadi@adancorporate.com',
    bio: 'Vinayak is a technology and transformation professional with 25+ years in global leadership roles across varied geographies and industry segments, including enterprise technology, cloud and IT services. His work covers enterprise architecture, cloud modernisation, cybersecurity, GCC transformation, digital platforms and global delivery leadership.',
    expertise: [],
    sectors: [],
    geographies: [],
    pillars: ['ai-digital', 'strategy-leadership'],
    needsPortrait: true,
    notes:
      'Homepage card and bio only. He has no profile page (the expected URL returns 404) and appears nowhere else on the old site, so there is no headshot, LinkedIn, expertise taxonomy or long biography for him. His role is printed as "Partner" with a specialism line of "Executive Director & Interim CTO", a second job title where every other card carries a specialism: confirm the correct title. Source bio read "Cloud Modernization"; converted to British spelling.',
  },
  {
    slug: 'nav-kaplish',
    name: 'Nav Kaplish',
    role: 'Partner',
    roleDetail: 'Digital, blockchain & risk',
    group: 'partner',
    city: 'London',
    country: 'United Kingdom',
    timeZone: 'Europe/London',
    email: 'nav.kaplish@adancorporate.com',
    linkedin: 'https://www.linkedin.com/in/navkaplish',
    bio: 'Nav is a business and technology executive with 18+ years of global corporate and entrepreneurial experience building and managing digital teams, and in leadership roles spanning governance, risk and compliance, audit, and the design and delivery of blockchain products. He is Head of Strategic Partnerships for the London chapter of the Government Blockchain Association and advises technology start-ups in the UK and India on venture strategy, market analysis and financing. He holds an MBA from London Business School.',
    expertise: [
      'Digital',
      'Startups - Growth Capital',
      'Risk Management',
      'Risk Strategy',
      'Enterprise Risk Management',
      'Target Due-Diligence',
      'Private Equity / Venture Capital',
      'Deal Strategy',
      'Business Strategy',
      'Corporate Strategy',
      'Coaching & Mentoring',
      'Blockchain',
      'Analytics',
      'Interim CEO / Managing Director',
      'Interim CMO',
    ],
    sectors: [
      'Technology',
      'Government & Public Services',
      'Banking & Capital Markets',
      'Financial Services',
      'Telecommunications',
    ],
    geographies: ['UK', 'India', 'Europe', 'South America'],
    pillars: ['ai-digital', 'risk-governance'],
    portrait: '/media/people/nav-kaplish.avif',
    needsPortrait: false,
    notes:
      'His bio names an outside affiliation, the Government Blockchain Association London chapter: confirm it should be surfaced.',
  },
  {
    slug: 'mike-kemball',
    name: 'Mike Kemball',
    role: 'Partner',
    roleDetail: 'Turnaround and growth',
    group: 'partner',
    city: 'London',
    country: 'United Kingdom',
    timeZone: 'Europe/London',
    email: 'Mike.Kemball@adancorporate.com',
    linkedin: 'https://www.linkedin.com/in/mikekemball/',
    bio: 'Mike is a sales transformation specialist with 30+ years as an interim sales director and managing director in 15+ organisations across telecoms, technology and industrial sectors in Europe, India, Africa and the Middle East. Client companies and subsidiaries were typically $10m to $300m in revenue, with sales teams of 10 to 250 people. He holds an MBA from London Business School (1980 cohort) and a BSc in physiology and biochemistry from Southampton University.',
    expertise: [
      'Transformation and Restructuring',
      'Deal Strategy',
      'Business Strategy',
      'Corporate Strategy',
      'Growth Strategy',
      'Marketing Strategy',
      'International Expansion',
      'NED & Board Advisory Services',
      'Interim CMO',
      'Alliances, JVs & Partnerships',
      'Market Entry',
    ],
    sectors: [
      'Telecommunications',
      'Engineering & Construction',
      'Industrial Manufacturing',
      'Pharma & Life Sciences',
      'Chemicals & Polymers',
      'Capital Projects & Infra',
    ],
    geographies: ['UK', 'USA', 'Middle East Asia', 'Asia Pacific'],
    pillars: ['strategy-leadership'],
    portrait: '/media/people/mike-kemball.avif',
    needsPortrait: false,
    notes:
      'Email is mixed-case in the source mailto. He is commented out of the homepage team grid: confirm he is still with the firm.',
  },
  {
    slug: 'suresh-nambiar',
    name: 'Suresh Nambiar',
    role: 'Partner',
    roleDetail: 'Procurement & logistics',
    group: 'partner',
    city: 'Manama',
    country: 'Bahrain',
    timeZone: 'Asia/Bahrain',
    email: 'suresh.nambiar@adancorporate.com',
    linkedin: 'https://www.linkedin.com/in/suresh-nambiar-047a0918/',
    bio: 'Suresh is a business executive with 30+ years of experience in general management, financial management, human resource management, procurement and logistics across packaging, pharmaceuticals, manufacturing and engineering, covering cost optimisation, fraud investigation, new product development and acquisitions. In his last role he was General Manager, Bahrain at Closure Systems International. He has worked on greenfield and expansion projects in the Philippines, the Middle East, India, Nepal and Egypt. He is a Chartered Accountant, a Company Secretary and holds a law degree from the University of Mumbai.',
    expertise: [
      'Private Equity',
      'Project Finance',
      'Debt Syndication',
      'Deal Strategy',
      'Commercial Negotiation',
      'Distressed Asset Management',
      'Transformation and Restructuring',
      'M&A',
      'Business Strategy',
      'NED & Board Advisory Services',
      'Working Capital and Trade Finance',
      'Interim CEO / Managing Director',
    ],
    sectors: [
      'Travel, Transport & Logistics',
      'Industrial Manufacturing',
      'Engineering & Construction',
      'Chemicals & Polymers',
      'Retail',
    ],
    geographies: ['Middle East Asia', 'USA', 'Europe', 'Africa', 'China'],
    pillars: ['corporate-finance', 'mergers-acquisitions'],
    portrait: '/media/people/suresh-nambiar.avif',
    needsPortrait: false,
    notes:
      'City printed as "Manama City, Bahrain"; normalised to Manama. Source bio used US spellings ("optimization", "specializes") and a stray full stop mid-list ("Devising SOPs. Cost Optimization Support"); corrected. He is commented out of the homepage team grid.',
  },
  {
    slug: 'thomas-peutz',
    name: 'Thomas Peutz',
    role: 'Partner',
    roleDetail: 'Sustainable energy',
    group: 'partner',
    city: 'Amsterdam',
    country: 'Netherlands',
    timeZone: 'Europe/Amsterdam',
    email: 'thomas.peutz@adancorporate.com',
    linkedin: 'https://www.linkedin.com/in/thomas-peutz-a7a44116/',
    bio: "Thomas is an entrepreneurial leader with 25+ years of experience in international management and organisational strategy, gained in the cultural sector and the creative industries, and serving on executive and non-executive boards. He has established, merged and grown organisations, a partnership and an investment fund, and advised national and local governments on innovation, urban development and the creative industries. He is a Sloan Fellow of London Business School and holds master's degrees from the VU University of Amsterdam.",
    expertise: [
      'Private Equity',
      'Transformation and Restructuring',
      'M&A',
      'Business Strategy',
      'Commercial Negotiation',
      'NED & Board Advisory Services',
      'Interim CEO / Managing Director',
      'Strategy & Planning',
      'Deal Strategy',
      'Corporate Strategy',
      'Board Advisors',
      'Marketing Strategy',
      'Market Entry',
    ],
    sectors: [
      'Government & Public Services',
      'Green Energy',
      'Social Sector',
      'Media & Entertainment',
      'Financial Services',
      'Technology',
      'Banking & Capital Markets',
      'Capital Projects & Infra',
      'Energy & Utilities',
      'Engineering & Construction',
    ],
    geographies: ['The Netherlands', 'UK'],
    pillars: ['strategy-leadership', 'corporate-finance'],
    portrait: '/media/people/thomas-peutz.avif',
    needsPortrait: false,
    notes:
      'Source expertise list repeated "Business Strategy"; deduplicated. His specialism is printed as "Sustainable Energy" but neither his bio nor his sector list leads on energy; confirm the specialism. The homepage version of his bio reads "experience in in C-suite roles" (doubled word).',
  },
  {
    slug: 'marco-salvini',
    name: 'Marco Salvini',
    role: 'Partner',
    roleDetail: 'Real estate',
    group: 'partner',
    city: 'Milan',
    country: 'Italy',
    timeZone: 'Europe/Rome',
    email: 'marco.salvini@adancorporate.com',
    linkedin: 'https://www.linkedin.com/in/marcosalvini/',
    bio: "Marco is a senior executive with 25+ years of real estate leadership, delivering strategy, transformational change and the turnaround of underperforming portfolios, assets and companies. He was CEO of AIG/Lincoln, AIG Global Real Estate in Italy, where as country managing partner he was accountable for a EUR 500 mn portfolio of shopping centres, logistics and industrial warehouses. He has also worked for Babcock & Brown, Amplifon Group, McDonald's and Jones Lang LaSalle. He is a member of the RICS.",
    expertise: [
      'Equity Financing',
      'Debt Financing',
      'M&A',
      'Private Equity',
      'NED & Board Advisory Services',
      'Special Situations',
      'Transformation and Restructuring',
      'Commercial Negotiation',
      'Distressed Asset Management',
      'Interim CEO / Managing Director',
      'Strategy & Planning',
      'Deal Strategy',
      'Business Strategy',
      'Corporate Strategy',
      'Board Advisors',
    ],
    sectors: [
      'Real Estate',
      'Social Sector',
      'Sovereign Investment Funds',
      'Banking & Capital Markets',
      'Capital Projects & Infra',
      'Financial Services',
    ],
    geographies: ['Italy', 'UK', 'Europe'],
    pillars: ['corporate-finance', 'mergers-acquisitions', 'strategy-leadership'],
    portrait: '/media/people/marco-salvini.avif',
    needsPortrait: false,
    notes:
      'Second city: London (printed "Milan & London"). His card says Milan and London while the last line of his bio says he is based in London: confirm the primary base.',
  },
  {
    slug: 'arun-shroff',
    name: 'Arun Shroff',
    role: 'Partner',
    group: 'partner',
    city: 'Pune',
    country: 'India',
    timeZone: 'Asia/Kolkata',
    email: 'arun.shroff@adancorporate.com',
    linkedin: 'https://in.linkedin.com/in/arun-shroff',
    bio: "Arun is a commercial and operations leader with four decades of experience across electrical precision parts manufacturing, agriculture, where he pioneered floriculture in India, and paper and paperboards. He has managed manufacturing and trading operations and relationships across countries, cultures, functions and hierarchies, and builds long-term customer and trade-fair relationships. His floriculture company won the APEDA award for excellence in exports five times. He holds a bachelor's degree in commerce from Calcutta University, St Xavier's College, Kolkata.",
    expertise: [
      'Operations',
      'Logistics',
      'Manufacturing Quality',
      'Growing and Sustaining Customer Relationships',
      'E2E Engagement',
    ],
    sectors: [
      'Electrical Precision Parts Manufacturing',
      'Agriculture Business',
      'Paper & Paperboards',
    ],
    geographies: ['India', 'Germany', 'Japan', 'The Netherlands'],
    pillars: ['strategy-leadership'],
    portrait: '/media/people/arun-shroff.avif',
    needsPortrait: false,
    notes:
      'Source bio had missing spaces after full stops and a truncated sentence, "He is a well-experienced executive who has a flair for creating." The truncated clause is dropped here; confirm what was intended. Headshot filenames contain spaces ("Arun Main Page.png", "Arun Team Page.png") and need renaming on migration.',
  },
  {
    slug: 'jean-bernard-tanqueray',
    name: 'Jean-Bernard Tanqueray',
    printedAs: 'Jean-Bernard (JB) Tanqueray',
    role: 'Partner',
    roleDetail: 'Family offices',
    group: 'partner',
    city: 'Paris',
    country: 'France',
    timeZone: 'Europe/Paris',
    email: 'jean-bernard@adancorporate.com',
    linkedin: 'https://www.linkedin.com/in/jbtanqueray/',
    bio: 'Jean-Bernard is a wealth and asset management executive with 20+ years of investment experience in private businesses and public capital markets for single family offices and institutional investors. He has designed top-down asset allocation and bottom-up fund selection processes for UK, US and French family offices, and trebled assets under management as a fund of hedge funds manager at Fortis Investments. He rated European asset managers at Fitch Ratings and holds an MBA from London Business School.',
    expertise: [
      'Family Offices Investments',
      'Startups - Growth Capital',
      'Fund Placement',
      'Equity Financing',
      'Private Equity',
      'Strategic Equity Partnerships',
      'Divestments and Exit Planning',
      'M&A',
      'Deal Strategy',
      'Business Strategy',
      'Corporate Strategy',
      'NED & Board Advisory Services',
      'Interim CEO / Managing Director',
      'Board Advisors',
    ],
    sectors: [
      'Asset & Wealth Management',
      'Sovereign Investment Funds',
      'Banking & Capital Markets',
      'Financial Services',
      'Technology',
    ],
    geographies: ['France', 'UK', 'Europe'],
    pillars: ['corporate-finance', 'mergers-acquisitions'],
    portrait: '/media/people/jean-bernard-tanqueray.avif',
    needsPortrait: false,
    notes:
      'Second city: London (printed "Paris & London"). Source bio repeated a sentence verbatim across its first two paragraphs, carried a doubled-quote artefact and read "has over the years, has developed"; all cleaned. Email format differs from the firm norm. He is commented out of the homepage team grid.',
  },
  {
    slug: 'craig-tingle',
    name: 'Craig Tingle',
    role: 'Partner',
    roleDetail: 'Real estate',
    group: 'partner',
    city: 'Miami',
    country: 'United States',
    timeZone: 'America/New_York',
    email: 'Craig.Tingle@adancorporate.com',
    linkedin: 'https://www.linkedin.com/in/craig-tingle-tingleandassociatespa-a5b93135/',
    bio: 'Craig is a board-certified real estate attorney with more than twenty-five years of legal experience, covering shopping centres and malls, apartment buildings, assisted living facilities, subdivisions, medical campuses and portfolio acquisitions. His work extends to the agricultural sector, including commercial farming and vineyards. He has managed corporate turnarounds, served as interim CEO and worked out distressed property. He has handled over 1,000 legal cases and appeared before the United States Supreme Court. He is a graduate of Washington University School of Law.',
    expertise: [
      'Private Equity',
      'Special Situations',
      'Distressed Asset Management',
      'Deal Strategy',
      'Interim CEO / Managing Director',
      'Company Valuation',
      'Transformation and Restructuring',
      'M&A',
      'International Expansion',
    ],
    sectors: [],
    geographies: [],
    pillars: ['corporate-finance', 'mergers-acquisitions'],
    portrait: '/media/people/craig-tingle.avif',
    needsPortrait: false,
    notes:
      'Second city: Dubai (profile prints "Miami and Dubai"; the homepage card prints "Florida & Dubai"). His sectors and geographies blocks are byte-identical to Kieran Bourke\'s (Banking & Capital Markets, Financial Services, Metals & Mining; Singapore, UK, South Africa) and contradict a US real-estate practice, so both are withheld pending confirmation. Source expertise repeated "Distressed Asset Management"; the sector names Real Estate, Capital Projects & Infra and Financial Services were dropped from the expertise list. His bio claims he "is pursuing an MBA from London Business School", a present-tense claim on an undated page, and that he has "closed billions of dollars in transactions"; neither is published here. His LinkedIn slug names his own firm, Tingle & Associates PA. Email is mixed-case in the source mailto. He is commented out of the homepage team grid.',
  },
  {
    slug: 'freddie-tshiaba',
    name: 'Freddie Tshiaba',
    role: 'Partner',
    roleDetail: 'International investments',
    group: 'partner',
    city: 'London',
    country: 'United Kingdom',
    timeZone: 'Europe/London',
    email: 'Freddie.Tshiaba@adancorporate.com',
    linkedin: 'https://www.linkedin.com/in/tshiaba/',
    bio: "Freddie is a senior business leader with 20+ years of experience helping investment banks, financial institutions, enterprise software companies and multinational corporates with strategic initiatives, business development, digital transformation, product management, liquidity risk and treasury management. He works in English and French and has worked across Europe, the Middle East, Central Africa and the United States. He holds an MBA from London Business School, a master's in business engineering from Liege HEC Management School and a master's in management science and entrepreneurship from the University of Liege.",
    expertise: [
      'Private Equity',
      'Special Situations',
      'Transformation and Restructuring',
      'Distressed Asset Management',
      'Corporate Finance',
      'M&A',
      'Company Valuation',
      'Commercial Negotiation',
      'Deal Strategy',
      'Business Strategy',
      'Corporate Strategy',
      'Risk Management',
      'Market Entry',
    ],
    sectors: [
      'Banking & Capital Markets',
      'Capital Projects & Infra',
      'Financial Services',
      'Private Equity',
      'Asset & Wealth Management',
      'Sovereign Investment Funds',
    ],
    geographies: ['Europe', 'Middle East Asia', 'Asia Pacific', 'Central Africa', 'UK', 'USA'],
    pillars: ['corporate-finance', 'mergers-acquisitions', 'risk-governance'],
    portrait: '/media/people/freddie-tshiaba.avif',
    needsPortrait: false,
    notes:
      'His specialism is printed as "International Investments" on the profile and "Corporate Finance" on the homepage. "Financial Services" and "Capital Projects & Infra" were listed as expertise and dropped as sector names. The 23-country list in his bio is not carried over. Email is mixed-case in the source mailto; the profile headshot file is "Freddie.png", which breaks the naming convention.',
  },
  {
    slug: 'raju-venkataraman',
    name: 'Raju Venkataraman',
    role: 'Partner',
    roleDetail: 'Strategy, executive coaching',
    group: 'partner',
    city: 'Singapore',
    country: 'Singapore',
    timeZone: 'Asia/Singapore',
    email: 'raju.v@adancorporate.com',
    linkedin: 'https://www.linkedin.com/in/rajuvenka1/',
    bio: 'Raju brings 30+ years of C-suite experience as CFO, head of strategy, business unit head and head of sales and distribution. His most recent corporate role was CFO and head of strategy of the Walt Disney Company for South East Asia. He is a member of the board of Special Olympics Asia-Pacific and chairs its audit committee. He now coaches senior leaders and corporate teams, is a Fellow of CIMA UK and is accredited by Marshall Goldsmith Stakeholder Centered Coaching.',
    expertise: [
      'NED & Board Advisory Services',
      'Executive Coaching',
      'Executive Transition',
      'Principled Negotiation Skills',
      'Leadership Identity',
      'Private Equity / Venture Capital',
      'Strategy & Planning',
      'Deal Strategy',
      'Business Strategy',
      'Corporate Strategy',
      'Growth Strategy',
      'Marketing Strategy',
      'Board Advisors',
      'International Expansion',
      'Market Entry',
    ],
    sectors: [
      'Media & Entertainment',
      'Retail',
      'Pharma & Life Sciences',
      'Technology',
      'Agriculture',
      'Industrial Manufacturing',
      'Chemicals & Polymers',
      'Private Equity',
      'Banking & Capital Markets',
      'Capital Projects & Infra',
    ],
    geographies: ['UK', 'India', 'USA', 'UAE', 'Asia Pacific'],
    pillars: ['strategy-leadership'],
    portrait: '/media/people/raju-venkataraman.avif',
    needsPortrait: false,
    notes:
      'Email format differs from the firm norm (raju.v@ rather than first.last@). His bio names an outside board role at Special Olympics Asia-Pacific: confirm it should be surfaced. His insight byline reads "Partner, Executive Coaching"; his card reads "Partner / Strategy, Executive Coaching".',
  },

  // ------------------------------------------------------------------------ directors
  {
    slug: 'ajay-sethi',
    name: 'Ajay Sethi',
    role: 'Director',
    roleDetail: 'Market development',
    group: 'director',
    city: 'London',
    country: 'United Kingdom',
    timeZone: 'Europe/London',
    email: 'sethi@adancorporate.com',
    linkedin: 'https://www.linkedin.com/in/ajay-sethi-91968b177/',
    bio: 'Ajay has 35+ years of experience across the management of growing businesses, sales and accountancy, with knowledge of business management, brand development, sales and marketing, product sourcing, fund-raising, accounting procedures and risk mitigation. He has established and grown an importing firm specialising in Kenyan products and a niche travel agency in central London, and has advised on the set-up of three branches of a confectionery franchise and on the expansion of a travel agency. He has a background in accountancy.',
    expertise: [
      'Project Finance',
      'Debt Financing',
      'Working Capital and Trade Finance',
      'Deal Strategy',
      'Business Strategy',
      'Commercial Negotiation',
    ],
    sectors: ['Retail', 'Industrial Manufacturing', 'Travel, Transport & Logistics'],
    geographies: ['UK', 'Africa'],
    pillars: ['corporate-finance', 'strategy-leadership'],
    portrait: '/media/people/ajay-sethi.avif',
    needsPortrait: false,
    notes:
      'Email format differs from the firm norm (sethi@ rather than first.last@). He is commented out of the homepage team grid: confirm he is still with the firm.',
  },
  {
    slug: 'sreeraman-p-s',
    name: 'Sreeraman P.S.',
    role: 'Director',
    roleDetail: 'Investments',
    group: 'director',
    city: 'Mumbai',
    country: 'India',
    timeZone: 'Asia/Kolkata',
    email: 'sreeraman.ps@adancorporate.com',
    linkedin: 'https://www.linkedin.com/in/sreeraman-p-s-6a4985127/',
    bio: 'Sreeraman has 15+ years of experience in capital markets and investment banking with small and medium enterprises, in sales, private wealth management, investment banking and equity advisory roles at Indiabulls, Motilal Oswal and Kotak Securities. He is experienced in supply chain finance for international buyers and suppliers. At Adan he is responsible for deal due diligence and implementation across India, covering fund placement, M&A, debt and equity fund raising and distressed asset management. He holds an MBA from MIT School of Management.',
    expertise: [
      'Family Offices Investments',
      'Fund Placement',
      'Private Equity',
      'Project Finance',
      'Working Capital and Trade Finance',
      'Factoring',
      'Invoice Discounting',
      'Alternative Financing',
      'Equity Financing',
      'Debt Financing',
      'M&A',
      'Startups - Growth Capital',
    ],
    sectors: [
      'Asset & Wealth Management',
      'Financial Services',
      'Private Equity',
      'Sovereign Investment Funds',
      'Banking & Capital Markets',
      'Capital Projects & Infra',
    ],
    geographies: ['India', 'South East Asia'],
    pillars: ['corporate-finance', 'mergers-acquisitions'],
    portrait: '/media/people/sreeraman-p-s.avif',
    needsPortrait: false,
  },

  // ------------------------------------------------------------------------- advisors
  {
    slug: 'kieran-bourke',
    name: 'Kieran Bourke',
    role: 'Partner',
    roleDetail: 'Commodities',
    group: 'advisor',
    city: 'Singapore',
    country: 'Singapore',
    timeZone: 'Asia/Singapore',
    email: 'kieran.bourke@adancorporate.com',
    linkedin: 'https://www.linkedin.com/in/kieran-bourke-006a511a/',
    bio: 'Kieran is a financial risk management specialist with 25+ years of global financial services experience across market, traded credit, operational, regulatory and enterprise risk management on four continents. He was a Managing Director at Standard Chartered Bank in London and Singapore, where he established the commodities market risk function from scratch. He has run multiple IMA model approval applications for global banks and managed regulatory audits. He is a Sloan Fellow of London Business School.',
    expertise: [
      'Risk Management',
      'Risk Strategy',
      'Enterprise Risk Management',
      'Target Due-Diligence',
      'Company Valuation',
      'Special Situations',
      'Transformation and Restructuring',
      'Interim CRO',
      'Coaching & Mentoring',
      'Private Equity',
      'Corporate Strategy',
      'Board Advisors',
    ],
    sectors: ['Banking & Capital Markets', 'Financial Services', 'Metals & Mining'],
    geographies: ['Singapore', 'UK', 'South Africa'],
    pillars: ['risk-governance'],
    portrait: '/media/people/kieran-bourke.avif',
    needsPortrait: false,
    notes:
      'Group set to advisor: his profile prints "Partner / Commodities" but the team page lists him under the "Advisors" heading. The homepage card calls him "Advisor / Risk Management" and his insight byline calls him "Partner, Commodities": three different titles for the same person, to be resolved. His sectors and geographies are duplicated on Craig Tingle\'s profile. His bio says four continents while the homepage counter says three.',
  },
  {
    slug: 'dipak-khot',
    name: 'Dipak Khot',
    role: 'Advisor',
    roleDetail: 'Global markets, treasury risk management',
    group: 'advisor',
    city: 'London',
    country: 'United Kingdom',
    timeZone: 'Europe/London',
    email: 'Dipak.Khot@adancorporate.com',
    linkedin: 'https://www.linkedin.com/in/dipak-khot-212623/',
    bio: 'Dipak is a banker with nearly three decades of experience in treasury and market risk management, with an understanding of global financial markets, FX and interest rate hedging and structuring, and liquidity management, which he applies to designing hedging strategies. He spent 25+ years in banking in locations across the world for Standard Chartered Bank, RBS, HSBC and, most recently, Syndicate Bank in London. He is a Chartered Accountant, a Cost and Management Accountant and a Chevening Scholar in banking and finance from the London School of Economics.',
    expertise: [
      'M&A',
      'Risk Management',
      'Private Equity',
      'Special Situations',
      'Transformation and Restructuring',
      'Corporate Finance',
      'Company Valuation',
      'Deal Strategy',
      'Business Strategy',
      'Corporate Strategy',
    ],
    sectors: [
      'Banking & Capital Markets',
      'Capital Projects & Infra',
      'Financial Services',
      'Private Equity',
      'Asset & Wealth Management',
      'Sovereign Investment Funds',
    ],
    geographies: ['UK', 'USA', 'Middle East Asia', 'Asia Pacific'],
    pillars: ['risk-governance', 'corporate-finance'],
    portrait: '/media/people/dipak-khot.avif',
    needsPortrait: false,
    notes:
      'His role line is printed with three slashes ("Advisor / Global Markets / Treasury Risk Management"); the two specialisms are joined here. "Financial Services" and "Capital Projects & Infra" were listed as expertise and dropped as sector names; his expertise block is otherwise identical to Roland Giebitz\'s and Edgar Garay\'s. Source read "Chevenings Scholar"; corrected to Chevening. Email is mixed-case in the source mailto.',
  },

  // ------------------------------------------------------------------------- analysts
  {
    slug: 'mahimaa-a-b',
    name: 'Mahimaa A.B',
    role: 'Financial Analyst',
    roleDetail: 'Marketing, accounting & finance',
    group: 'analyst',
    city: 'London',
    country: 'United Kingdom',
    timeZone: 'Europe/London',
    email: 'mahima.baindur@adancorporate.com',
    bio: 'Mahimaa is a marketing and strategy professional. Her experience spans brand campaigns, partnerships, business strategy and market research across the education and corporate sectors, with a focus on consumer marketing, FMCG insight, brand building and strategy-led business growth.',
    expertise: [],
    sectors: [],
    geographies: [],
    pillars: ['strategy-leadership'],
    needsPortrait: true,
    notes:
      'Homepage card and bio only: no profile page, so no headshot, LinkedIn or taxonomy exists for her. Her card title is Financial Analyst but her bio describes a marketing and strategy professional: confirm the title. Her printed name ("Mahimaa A.B") and her email prefix ("mahima.baindur") disagree on both spelling and surname.',
  },
  {
    slug: 'shreyash-gandhi',
    name: 'Shreyash Gandhi',
    role: 'Financial Analyst',
    roleDetail: 'M&A, accounting & finance',
    group: 'analyst',
    city: 'Mumbai',
    country: 'India',
    timeZone: 'Asia/Kolkata',
    email: 'shreyash.gandhi@adancorporate.com',
    linkedin: 'https://www.linkedin.com/in/cashreyash/',
    bio: "Shreyash is a Chartered Accountant and finance professional with experience in business valuation, financial due diligence and strategic advisory. In Deloitte's valuations team he led and supported cross-border engagements across Europe, the Middle East, Canada and Scandinavia, advising clients in infrastructure, FMCG, technology and retail. His work spans transaction structuring, impairment testing, start-up valuations and market analysis.",
    expertise: ['M&A', 'Accounting', 'Finance'],
    sectors: ['Banking & Capital Markets', 'Financial Services', 'Private Equity'],
    geographies: ['India', 'UK'],
    pillars: ['corporate-finance', 'mergers-acquisitions'],
    portrait: '/media/people/shreyash-gandhi.avif',
    needsPortrait: false,
    notes:
      'City is Mumbai on the profile page and "India" on the homepage. Headshot filename contains spaces and needs renaming on migration.',
  },
  {
    slug: 'harsh-katiyar',
    name: 'Harsh Katiyar',
    role: 'Corporate Intern',
    roleDetail: 'Technology',
    group: 'analyst',
    city: 'India',
    country: 'India',
    timeZone: 'Asia/Kolkata',
    email: 'katiyarh76@gmail.com',
    bio: 'Harsh is a computer science and business systems undergraduate. His experience spans full-stack engineering, distributed systems, blockchain, cloud computing, database architecture, system design and AI-driven solutions, with proficiency in Java, C/C++, JavaScript, Node.js, SQL and RESTful architectures.',
    expertise: [],
    sectors: [],
    geographies: [],
    pillars: ['ai-digital'],
    needsPortrait: true,
    notes:
      'Homepage card and bio only: no profile page, headshot, LinkedIn or taxonomy. His email is a personal Gmail address, the only non-firm address on the site: a firm address is needed before publication. He is a Corporate Intern (Technology); the schema has no intern group, so he sits with the analysts. City printed only as "India". Confirm whether interns should appear on the new site at all.',
  },
  {
    slug: 'varun-nadkarni',
    name: 'Varun Nadkarni',
    role: 'Financial Analyst',
    group: 'analyst',
    city: 'India',
    country: 'India',
    timeZone: 'Asia/Kolkata',
    email: 'varun.nadkarni@adancorporate.com',
    linkedin: 'https://www.linkedin.com/in/varun-nadkarni-43843a104/',
    bio: 'Varun has more than six years of experience in accounts and finance. He holds an MBA in finance and international business from Amity University, India, and has a particular interest in equities, mutual funds and the analysis of company financial statements, which he uses to help people make better financial decisions.',
    expertise: ['Accounting', 'Finance'],
    sectors: ['Capital Markets', 'Financial Services', 'Taxation'],
    geographies: ['India'],
    pillars: ['corporate-finance'],
    portrait: '/media/people/varun-nadkarni.avif',
    needsPortrait: false,
    // The two published versions of his bio disagree on the one number in it.
    notes:
      'Years of experience conflict: his profile page says "more than 6 years", the homepage says "more than 2.5 years". The profile figure is used here pending confirmation. City printed only as "India" on both pages: confirm his base. Headshot filenames contain spaces ("Varun Photo Index.png", "Varun Photo Team.png").',
  },
  {
    slug: 'heena-tilwani',
    name: 'Heena Tilwani',
    role: 'Financial Analyst',
    group: 'analyst',
    city: 'Gurgaon',
    country: 'India',
    timeZone: 'Asia/Kolkata',
    email: 'heena.tilwani@adancorporate.com',
    linkedin: 'https://www.linkedin.com/in/heena-tilwani-b73a71168/',
    bio: 'Heena is a financial analyst and intermediate accountant with over five years of experience in financial accounting, analysis and reporting. She prepares monthly and quarterly reports and performance KPIs, and her interests are financial modelling, process improvement and data analytics.',
    expertise: ['Accounting', 'Finance'],
    sectors: ['Banking & Capital Markets', 'Financial Services', 'Accounting Services'],
    geographies: ['UK', 'India'],
    pillars: ['corporate-finance'],
    portrait: '/media/people/heena-tilwani.avif',
    needsPortrait: false,
    notes:
      'City is Gurgaon on the profile page and "India" on the homepage. Source read "over 5+ years"; normalised. Headshot filename contains spaces and needs renaming on migration.',
  },
] satisfies unknown[];

export const people = z.array(Person).parse(data);
