/** Generated by scripts/media/portraits.ts. Do not edit by hand. */

export interface PortraitAsset {
  blurDataURL: string;
  width: number;
  height: number;
}

/** Widths actually emitted. The source avatars do not support more. */
export const portraitWidths = [240, 320] as const;

export const portraits: Record<string, PortraitAsset> = {
  'ajay-mavinkurve': {
    blurDataURL:
      'data:image/webp;base64,UklGRkYAAABXRUJQVlA4IDoAAACwAQCdASoMAA8ABABoJaQAAhuxrF8gAP7pTPBuCasYqCjuoV3EwFq6lNbHWC8uBKTK6qzSSfyAAAAA',
    width: 180,
    height: 225,
  },
  'ajay-sethi': {
    blurDataURL:
      'data:image/webp;base64,UklGRj4AAABXRUJQVlA4IDIAAAAQAgCdASoMAA8ABABoJaQAAl3Q4bUtxsQAAP6Y5/u3+NuhUp5J5j4Ctp4uC4ckFzAAAA==',
    width: 338,
    height: 422,
  },
  'arun-shroff': {
    blurDataURL:
      'data:image/webp;base64,UklGRj4AAABXRUJQVlA4IDIAAACwAQCdASoMAA8ABABoJaQAAc+riFAAAP7ceNjrfYnWrwlGV7KIGCsY9Vgf1AkQOAAAAA==',
    width: 407,
    height: 508,
  },
  'craig-tingle': {
    blurDataURL:
      'data:image/webp;base64,UklGRkYAAABXRUJQVlA4IDoAAAAQAgCdASoMAA8ABABoJaQAAuzXs9MFT7SMAPlIWYrib3AnH0qtenulVH7j03MpBMnNYVKvhj/FKnAA',
    width: 238,
    height: 297,
  },
  'dipak-khot': {
    blurDataURL:
      'data:image/webp;base64,UklGRkgAAABXRUJQVlA4IDwAAADQAQCdASoMAA8ABABoJaQAAlmF87w5gAD+1dqmxm+1YcjRWpyC0e5C8DbvyGStnxZDiSXru7W4VyE6AAA=',
    width: 234,
    height: 292,
  },
  'edgar-garay': {
    blurDataURL:
      'data:image/webp;base64,UklGRkgAAABXRUJQVlA4IDwAAABwAQCdASoMAA8ABABoJaQAAk8YAADibsR6tBDty7bEli+maVMwsR7Ire/CeeSRLzaW7DDNLtD25+E8QAA=',
    width: 251,
    height: 313,
  },
  'freddie-tshiaba': {
    blurDataURL:
      'data:image/webp;base64,UklGRkYAAABXRUJQVlA4IDoAAADwAQCdASoMAA8ABABoJaQAAlvLT+SaAAAA+XJ1MdTQvB0SpFLLr3VN885UhQRY5MHdqmgbdkxdaAAA',
    width: 145,
    height: 181,
  },
  'george-christelis': {
    blurDataURL:
      'data:image/webp;base64,UklGRkYAAABXRUJQVlA4IDoAAABwAQCdASoMAA8ABABoJaQAAmekAAD+6YzKS5oeO+jH7DvEJ5yjISaRLWONsB1Kvq9mwmdH6FCWAAAA',
    width: 162,
    height: 202,
  },
  'heena-tilwani': {
    blurDataURL:
      'data:image/webp;base64,UklGRkgAAABXRUJQVlA4IDwAAADwAQCdASoMAA8ABABoJaQAAt0C3L4hYAAA/on4DuWLzUUu761awcj62xaNQiw7A1rBUPLZ4tbAVuOAAAA=',
    width: 145,
    height: 181,
  },
  'jean-bernard-tanqueray': {
    blurDataURL:
      'data:image/webp;base64,UklGRkYAAABXRUJQVlA4IDoAAAAQAgCdASoMAA8ABABoJaQAAiaCYtpv3ewAAP7BzHrZaC3o29ikx9xXIBvpQqM3wAidYuyRZZY3gAAA',
    width: 210,
    height: 262,
  },
  'keshav-adya': {
    blurDataURL:
      'data:image/webp;base64,UklGRkwAAABXRUJQVlA4IEAAAADwAQCdASoMAA8ABABoJaQAAxYRjRoIYJAA4m6oxxCPspuBaY25rP3aMbZWPXs7/mMe7aAWmciBqK4JtwxUmIAA',
    width: 216,
    height: 270,
  },
  'kieran-bourke': {
    blurDataURL:
      'data:image/webp;base64,UklGRkgAAABXRUJQVlA4IDwAAACwAQCdASoMAA8ABABoJaQAAhovXqwAAPw7LXUzYuae4VT9ZJQ3iYTKqfQNwfCKmruu2VFZJnQ5sEoAAAA=',
    width: 246,
    height: 307,
  },
  'marco-salvini': {
    blurDataURL:
      'data:image/webp;base64,UklGRkYAAABXRUJQVlA4IDoAAADwAQCdASoMAA8ABABoJaQAAlwwKvEsIAAA/reY0sgNNZCg/lb3V4erIRJmoq5SNqW//VBaSx5twAAA',
    width: 344,
    height: 430,
  },
  'mike-kemball': {
    blurDataURL:
      'data:image/webp;base64,UklGRkQAAABXRUJQVlA4IDgAAADwAQCdASoMAA8ABABoJaQAAn/g8k13eYAA/CajLcfvqNAr2JGS0D79nyvGTnvVAePCGffMvRIAAA==',
    width: 236,
    height: 295,
  },
  'nav-kaplish': {
    blurDataURL:
      'data:image/webp;base64,UklGRlAAAABXRUJQVlA4IEQAAAAQAgCdASoMAA8ABABoJaQAAt1u1s0DB2EAAP6+VjoCzAQ6nuMs/bmax/1v1uv1aTzoo0GHFnvXR5seIQSA2xRumAAAAA==',
    width: 233,
    height: 291,
  },
  'neeraj-arora': {
    blurDataURL:
      'data:image/webp;base64,UklGRjoAAABXRUJQVlA4IC4AAACwAQCdASoMAA8ABABoJaQAAfInChAAAMvggxzwlrlu1s4icir07jx2GUH3AAAA',
    width: 140,
    height: 175,
  },
  'preethi-hari': {
    blurDataURL:
      'data:image/webp;base64,UklGRk4AAABXRUJQVlA4IEIAAACQAQCdASoMAA8ABABoJaQAAsRmdoAA9r5a4Jkn2rWg+8d/eFx8BFkyaWPI63UyysM0sRaDS7hI9/LOLR+6cH4HmAA=',
    width: 247,
    height: 308,
  },
  'raju-venkataraman': {
    blurDataURL:
      'data:image/webp;base64,UklGRk4AAABXRUJQVlA4IEIAAAAQAgCdASoMAA8ABABoJaQAAq+WWJ7/NXAAAP7drq8fOstoTNmhYcq8DUvj92eT06MltIPh8g1/pPbwbnFEG7OR4AA=',
    width: 200,
    height: 250,
  },
  'rauf-akhundov': {
    blurDataURL:
      'data:image/webp;base64,UklGRkQAAABXRUJQVlA4IDgAAACwAQCdASoMAA8ABABoJaQAApvS/wQAAP7MTBQZk953ojbQJc4i2BusiD8lYdZr2+C3jgs2hsAAAA==',
    width: 169,
    height: 211,
  },
  'roland-giebitz': {
    blurDataURL:
      'data:image/webp;base64,UklGRkwAAABXRUJQVlA4IEAAAADwAQCdASoMAA8ABABoJaQAAuySAYKZ8YAA4n4Wvr075Ux5pN834tzlNgyHaok2ca/GHIUQ6xk6awMTLt34AAAA',
    width: 253,
    height: 316,
  },
  'sabapaty-suryanarayanan': {
    blurDataURL:
      'data:image/webp;base64,UklGRkIAAABXRUJQVlA4IDYAAACwAQCdASoMAA8ABABoJaQAAkrVzA8AAP28I600TzB+0VMeWdF/4JqfZshJRBL29xRbcCAAAAA=',
    width: 180,
    height: 225,
  },
  'sandeep-bhat': {
    blurDataURL:
      'data:image/webp;base64,UklGRkYAAABXRUJQVlA4IDoAAACQAQCdASoMAA8ABABoJaQAAUooP8AA/gbs71xtXRNJ2cmMVsNXTM5yLVdTCYHD9aOcpBXaW/yBSAAA',
    width: 167,
    height: 208,
  },
  'shreyash-gandhi': {
    blurDataURL:
      'data:image/webp;base64,UklGRj4AAABXRUJQVlA4IDIAAADQAQCdASoMAA8ABABoJaQAAtsZUbROAAD+TXINe9x54LTXSlGJPQMi6Iijx3ePKnAAAA==',
    width: 146,
    height: 182,
  },
  'sreeraman-p-s': {
    blurDataURL:
      'data:image/webp;base64,UklGRkQAAABXRUJQVlA4IDgAAADwAQCdASoMAA8ABABoJaQAAq9hGz1ZfUAA/sBAf7f8BjdjXHymfVrUQkMzwSyG+oqnQP3oIUAAAA==',
    width: 210,
    height: 262,
  },
  'suresh-nambiar': {
    blurDataURL:
      'data:image/webp;base64,UklGRkgAAABXRUJQVlA4IDwAAADwAQCdASoMAA8ABABoJaQAAtvKubpCyvwA/qxZeU31llB8sxIj7fh83EaTTPT0DtVG8NwIE/XXvrYAAAA=',
    width: 226,
    height: 282,
  },
  'thomas-peutz': {
    blurDataURL:
      'data:image/webp;base64,UklGRkAAAABXRUJQVlA4IDQAAADwAQCdASoMAA8ABABoJaQAAsSOOnP55AAA/nIEUWjhrbQzrQH0WmbEga6uNhjw6leSuQAA',
    width: 208,
    height: 260,
  },
  'thu-nga-haskovcova': {
    blurDataURL:
      'data:image/webp;base64,UklGRlAAAABXRUJQVlA4IEQAAAAQAgCdASoMAA8ABABoJaQAAtzO2VpqvWgAAP7Cr2HTQ6GuOdZPJE1Ut6nN3hGLHHtT7sAlAfHH0TlzG8kTjnwSvgAAAA==',
    width: 392,
    height: 490,
  },
  'varun-nadkarni': {
    blurDataURL:
      'data:image/webp;base64,UklGRkgAAABXRUJQVlA4IDwAAADQAQCdASoMAA8ABABoJaQAAt1wKs9KgAD+wLwQqJxT6LhfbXYRTsLksIx2e2wupOJ9ODk1fu57LBzYAAA=',
    width: 173,
    height: 216,
  },
  'vernon-d-cruz': {
    blurDataURL:
      'data:image/webp;base64,UklGRkQAAABXRUJQVlA4IDgAAACwAQCdASoMAA8ABABoJaQAAtxSmugAAPAOVrnNHicEOuV+ceSjtmcxlWPF0W03VDLYSYGkjoAAAA==',
    width: 232,
    height: 290,
  },
};

/** People with no usable photograph. They get a typographic monogram. */
export const missingPortraits: string[] = [];
