/**
 * Completed transactions and current mandates, carried over from the old site.
 *
 * Everything here traces to content/_source/transactions.md. The old cards were
 * already anonymised; they stay that way. Superlatives the source asserts but
 * cannot evidence ("the world's largest", "Asia's largest") are softened to
 * "one of", never dropped and never strengthened. Years appear only on the
 * three deals that state one.
 *
 * Band boundaries for completed transactions are defined here as: under
 * US$10m is below 10m; US$10m to US$50m is 10m up to and including 50m;
 * US$50m to US$200m is above 50m up to and including 200m; over US$200m is
 * above 200m. The old site never defined them, which is why deals sitting
 * exactly on a boundary were unreachable (source FLAG-L9).
 */
import { z } from 'zod';
import { Mandate, Transaction } from './schema';

const transactionData = [
  {
    id: 'theme-park-strategy-project-finance',
    headline: 'Business strategy and project finance advice for one of Asia’s leading theme parks.',
    corridor: 'Within Asia',
    regions: ['Asia'],
    sectors: ['Hospitality & Leisure', 'Media & Entertainment'],
    roles: ['Project finance', 'Equity financing', 'Business strategy'],
    pillars: ['corporate-finance', 'strategy-leadership'],
    value: 'Undisclosed',
    valueUsd: null,
    band: 'Undisclosed',
  },
  {
    id: 'insurance-aggregator-acquisition',
    headline:
      'Advisory on the acquisition of one of Asia’s leading online aggregators of insurance products.',
    corridor: 'Within Asia',
    regions: ['Asia'],
    sectors: ['Insurance', 'Technology'],
    roles: ['Sell-side', 'Equity financing', 'Deal strategy'],
    pillars: ['mergers-acquisitions', 'corporate-finance'],
    value: 'Undisclosed',
    valueUsd: null,
    band: 'Undisclosed',
  },
  {
    id: 'clean-energy-debt-invoice-discounting',
    headline:
      'Debt financing and invoice discounting for one of Europe’s leading clean energy providers to mid-sized businesses.',
    corridor: 'Asia to Europe',
    regions: ['Europe', 'Asia'],
    sectors: ['Green Energy', 'Technology'],
    roles: ['Debt financing', 'Invoice discounting'],
    pillars: ['corporate-finance'],
    value: 'Undisclosed',
    valueUsd: null,
    band: 'Undisclosed',
  },
  {
    id: 'ipo-film-production-distribution',
    headline:
      'End-to-end advisory on the initial public offering of one of Asia’s largest film production and distribution businesses.',
    corridor: 'Asia to Europe and the US',
    regions: ['Europe', 'Asia', 'Americas'],
    sectors: ['Media & Entertainment'],
    roles: ['IPO', 'Business strategy', 'Credit ratings assistance'],
    pillars: ['corporate-finance', 'strategy-leadership'],
    value: 'US$1bn',
    valueUsd: 1_000_000_000,
    band: 'Over US$200m',
  },
  {
    id: 'technical-consultancy-project-funding',
    headline:
      'Selection of project funding partners for a multinational technical consultancy based in Asia.',
    corridor: 'Within Asia',
    regions: ['Asia'],
    sectors: ['Technology'],
    roles: ['Project finance', 'Deal strategy'],
    pillars: ['corporate-finance', 'mergers-acquisitions'],
    value: 'US$200m',
    valueUsd: 200_000_000,
    band: 'US$50m to US$200m',
  },
  {
    id: 'real-estate-pe-fund-placement',
    headline: 'Fund placement for a real estate private equity fund in Europe.',
    corridor: 'Within Europe',
    regions: ['Europe'],
    sectors: ['Private Equity'],
    roles: ['Fund placement', 'Private equity', 'Corporate strategy'],
    pillars: ['corporate-finance', 'strategy-leadership'],
    value: 'US$200m',
    valueUsd: 200_000_000,
    band: 'US$50m to US$200m',
  },
  {
    id: 'mining-corporate-debt-tax',
    headline:
      'Corporate debt raising and sales tax advisory for one of Asia’s largest private mining companies, an investor in renewable energy.',
    corridor: 'Within Asia',
    regions: ['Asia'],
    sectors: ['Metals & Mining', 'Green Energy'],
    roles: ['Debt financing', 'Project finance', 'Deal strategy'],
    pillars: ['corporate-finance', 'mergers-acquisitions'],
    value: 'US$150m',
    valueUsd: 150_000_000,
    band: 'US$50m to US$200m',
  },
  {
    id: 'ipo-adhesives-manufacturer',
    headline:
      'End-to-end advisory on the initial public offering of one of Asia’s leading adhesives manufacturers.',
    corridor: 'Within Asia',
    regions: ['Asia'],
    sectors: ['Chemicals & Polymers', 'Industrial Manufacturing'],
    roles: ['IPO', 'Credit ratings assistance', 'Deal strategy'],
    pillars: ['corporate-finance', 'mergers-acquisitions'],
    value: 'US$150m',
    valueUsd: 150_000_000,
    band: 'US$50m to US$200m',
  },
  {
    id: 'healthcare-pe-fund-placement',
    headline:
      'Fund placement for a healthcare-focused private equity fund, constituted as an alternative investment fund in Asia.',
    corridor: 'Within Asia',
    regions: ['Asia'],
    sectors: ['Private Equity', 'Healthcare Systems & Services'],
    roles: ['Private equity', 'Fund placement', 'Corporate strategy'],
    pillars: ['corporate-finance', 'strategy-leadership'],
    value: 'US$125m',
    valueUsd: 125_000_000,
    band: 'US$50m to US$200m',
  },
  {
    id: 'ma-vfx-3d-studio',
    headline:
      'End-to-end mergers and acquisitions advisory for one of the world’s largest visual effects and 3D studios, in Europe.',
    corridor: 'Within Europe',
    regions: ['Europe'],
    sectors: ['Media & Entertainment', 'Technology'],
    roles: ['Sell-side', 'Private equity', 'Deal strategy'],
    pillars: ['mergers-acquisitions', 'corporate-finance'],
    value: 'US$100m',
    valueUsd: 100_000_000,
    band: 'US$50m to US$200m',
    year: 2015,
  },
  {
    id: 'ipo-private-industrial-group',
    headline:
      'End-to-end advisory on the initial public offering of one of Asia’s largest private companies, an investor in renewable energy.',
    corridor: 'Within Asia',
    regions: ['Asia'],
    sectors: ['Metals & Mining', 'Industrial Manufacturing'],
    roles: ['IPO', 'Credit ratings assistance', 'Business strategy'],
    pillars: ['corporate-finance', 'strategy-leadership'],
    value: 'US$77m',
    valueUsd: 77_000_000,
    band: 'US$50m to US$200m',
  },
  {
    id: 'ma-augmented-reality',
    headline:
      'End-to-end mergers and acquisitions advisory for an augmented reality business in Europe.',
    corridor: 'Within Europe',
    regions: ['Europe'],
    sectors: ['Technology'],
    roles: ['Sell-side', 'Private equity', 'Deal strategy'],
    pillars: ['mergers-acquisitions', 'corporate-finance'],
    value: 'US$50m',
    valueUsd: 50_000_000,
    band: 'US$10m to US$50m',
    year: 2016,
  },
  {
    id: 'interim-cfo-virtual-reality',
    headline:
      'Interim chief financial officer and strategy executive for a virtual reality business in Europe.',
    corridor: 'Within Europe',
    regions: ['Europe'],
    sectors: ['Technology'],
    roles: ['Deal strategy'],
    pillars: ['mergers-acquisitions'],
    value: 'US$50m',
    valueUsd: 50_000_000,
    band: 'US$10m to US$50m',
  },
  {
    id: 'sale-hospital-group',
    headline: 'Sell-side advisory on the sale of a tertiary care hospital group in Asia.',
    corridor: 'Within Asia',
    regions: ['Asia'],
    sectors: ['Healthcare Systems & Services'],
    roles: ['Sell-side', 'Private equity', 'Deal strategy'],
    pillars: ['mergers-acquisitions', 'corporate-finance'],
    value: 'US$50m',
    valueUsd: 50_000_000,
    band: 'US$10m to US$50m',
  },
  {
    id: 'mbo-ecommerce-marketplace',
    headline:
      'Debt financing and deal strategy for the management buy-out of an e-commerce marketplace in Europe.',
    corridor: 'Within Europe',
    regions: ['Europe'],
    sectors: ['Retail', 'Technology'],
    roles: ['Debt financing', 'Deal strategy'],
    pillars: ['corporate-finance', 'mergers-acquisitions'],
    value: 'US$30m',
    valueUsd: 30_000_000,
    band: 'US$10m to US$50m',
  },
  {
    id: 'sale-gold-precious-metals',
    headline:
      'Advisory on the sale of a gold and precious metals mining business in the United States.',
    corridor: 'Within the Americas',
    regions: ['Americas'],
    sectors: ['Metals & Mining'],
    roles: ['Private equity', 'Deal strategy'],
    pillars: ['corporate-finance', 'mergers-acquisitions'],
    value: 'US$30m',
    valueUsd: 30_000_000,
    band: 'US$10m to US$50m',
  },
  {
    id: 'working-capital-vfx-3d',
    headline:
      'Working capital and debt financing for a visual effects and 3D studio operating across Asia and Europe.',
    corridor: 'Asia to Europe',
    regions: ['Asia', 'Europe'],
    sectors: ['Media & Entertainment', 'Technology'],
    roles: ['Working capital', 'Debt financing', 'Deal strategy'],
    pillars: ['corporate-finance', 'mergers-acquisitions'],
    value: 'US$20m',
    valueUsd: 20_000_000,
    band: 'US$10m to US$50m',
  },
  {
    id: 'funding-augmented-reality-acquisition',
    headline:
      'Early stage and expansion funding for the acquisition of an augmented reality business in Asia.',
    corridor: 'Within Asia',
    regions: ['Asia'],
    sectors: ['Technology'],
    roles: ['Business strategy'],
    pillars: ['strategy-leadership'],
    value: 'US$20m',
    valueUsd: 20_000_000,
    band: 'US$10m to US$50m',
  },
  {
    id: 'antibiotics-lender-review-debt-raise',
    headline:
      'Represented an antibiotic drug manufacturer in Asia through a review by a financial institution and the debt raise that followed.',
    corridor: 'Within Asia',
    regions: ['Asia'],
    sectors: ['Pharma & Life Sciences'],
    roles: ['Debt financing', 'Project finance', 'Deal strategy'],
    pillars: ['corporate-finance', 'mergers-acquisitions'],
    value: 'US$16m',
    valueUsd: 16_000_000,
    band: 'US$10m to US$50m',
  },
  {
    id: 'sale-medical-diagnostics',
    headline: 'Advisory on the sale of a leading medical diagnostics business in Asia.',
    corridor: 'Within Asia',
    regions: ['Asia'],
    sectors: ['Healthcare Systems & Services'],
    roles: ['Private equity', 'Deal strategy'],
    pillars: ['corporate-finance', 'mergers-acquisitions'],
    value: 'US$15m',
    valueUsd: 15_000_000,
    band: 'US$10m to US$50m',
  },
  {
    id: 'modelling-sustainable-products-platform',
    headline:
      'Financial modelling and business plan review for a start-up platform promoting sustainable and energy-efficient products in Asia.',
    corridor: 'Within Asia',
    regions: ['Asia'],
    sectors: ['Technology', 'Retail'],
    roles: ['Private equity', 'Deal strategy'],
    pillars: ['corporate-finance', 'mergers-acquisitions'],
    value: 'US$10m',
    valueUsd: 10_000_000,
    band: 'US$10m to US$50m',
  },
  {
    id: 'funding-flower-exporter',
    headline: 'Debt and project finance for one of Asia’s largest flower exporters.',
    corridor: 'Within Asia',
    regions: ['Asia'],
    sectors: ['Retail', 'Agriculture'],
    roles: ['Debt financing', 'Project finance', 'Deal strategy'],
    pillars: ['corporate-finance', 'mergers-acquisitions'],
    value: 'US$10m',
    valueUsd: 10_000_000,
    band: 'US$10m to US$50m',
    year: 1992,
  },
  {
    id: 'it-development-acquisition-fundraising',
    headline: 'Acquisition and fundraising advisory for an IT development business, globally.',
    corridor: 'Global',
    regions: ['Global'],
    sectors: ['Technology', 'Financial Services'],
    roles: ['Project finance', 'Business strategy'],
    pillars: ['corporate-finance', 'strategy-leadership'],
    value: 'US$10m',
    valueUsd: 10_000_000,
    band: 'US$10m to US$50m',
  },
  {
    id: 'debt-glass-vials-supplier',
    headline:
      'Debt funding for a supplier of glass vials and ampoules to the pharmaceutical industry in Asia.',
    corridor: 'Within Asia',
    regions: ['Asia'],
    sectors: ['Industrial Manufacturing'],
    roles: ['Debt financing', 'Business strategy', 'Deal strategy'],
    pillars: ['corporate-finance', 'strategy-leadership', 'mergers-acquisitions'],
    value: 'US$10m',
    valueUsd: 10_000_000,
    band: 'US$10m to US$50m',
  },
  {
    id: 'debt-construction-company',
    headline: 'Debt funding for a leading construction company in Asia.',
    corridor: 'Within Asia',
    regions: ['Asia'],
    sectors: ['Engineering & Construction'],
    roles: ['Debt financing', 'Business strategy', 'Deal strategy'],
    pillars: ['corporate-finance', 'strategy-leadership', 'mergers-acquisitions'],
    value: 'US$10m',
    valueUsd: 10_000_000,
    band: 'US$10m to US$50m',
  },
  {
    id: 'vc-antibiotics-manufacturer',
    headline:
      'Venture capital funding for the establishment of an antibiotic drug manufacturer in Asia.',
    corridor: 'Within Asia',
    regions: ['Asia'],
    sectors: ['Pharma & Life Sciences'],
    roles: ['Private equity and venture capital', 'Startups and growth capital', 'Deal strategy'],
    pillars: ['corporate-finance', 'mergers-acquisitions'],
    value: 'US$8m',
    valueUsd: 8_000_000,
    band: 'Under US$10m',
  },
  {
    id: 'debt-steel-ingot-plant',
    headline:
      'Debt financing and business strategy for a 150,000 tonne per annum steel ingot plant in Asia.',
    corridor: 'Within Asia',
    regions: ['Asia'],
    sectors: ['Metals & Mining'],
    roles: ['Debt financing', 'Business strategy', 'Deal strategy'],
    pillars: ['corporate-finance', 'strategy-leadership', 'mergers-acquisitions'],
    value: 'US$8m',
    valueUsd: 8_000_000,
    band: 'Under US$10m',
  },
  {
    id: 'ipo-rights-issue-steel-ingot',
    headline:
      'End-to-end advisory on the initial public offering and rights issue of a 150,000 tonne per annum steel ingot plant in Asia.',
    corridor: 'Within Asia',
    regions: ['Asia'],
    sectors: ['Metals & Mining'],
    roles: ['IPO', 'Credit ratings assistance', 'Business strategy'],
    pillars: ['corporate-finance', 'strategy-leadership'],
    value: 'US$8m',
    valueUsd: 8_000_000,
    band: 'Under US$10m',
  },
  {
    id: 'working-capital-pharma',
    headline: 'Working capital finance for a pharmaceutical manufacturer in Asia.',
    corridor: 'Within Asia',
    regions: ['Asia'],
    sectors: ['Pharma & Life Sciences'],
    roles: ['Working capital', 'Business strategy', 'Deal strategy'],
    pillars: ['corporate-finance', 'strategy-leadership', 'mergers-acquisitions'],
    // Published as $7.69 million on the old site. Kept to the cent rather than
    // rounded to US$7.7m, so the figure still matches its source.
    value: 'US$7.69m',
    valueUsd: 7_690_000,
    band: 'Under US$10m',
  },
  {
    id: 'ipo-chemicals-manufacturer',
    headline: 'Advisory on the initial public offering of a chemicals manufacturer in Asia.',
    corridor: 'Within Asia',
    regions: ['Asia'],
    sectors: ['Chemicals & Polymers'],
    roles: ['IPO', 'Credit ratings assistance', 'Business strategy'],
    pillars: ['corporate-finance', 'strategy-leadership'],
    value: 'US$7.69m',
    valueUsd: 7_690_000,
    band: 'Under US$10m',
  },
  {
    id: 'ipo-alloy-steel-products',
    headline:
      'Advisory on the initial public offering of an alloy steel products manufacturer in Asia.',
    corridor: 'Within Asia',
    regions: ['Asia'],
    sectors: ['Metals & Mining'],
    roles: ['IPO', 'Credit ratings assistance', 'Business strategy'],
    pillars: ['corporate-finance', 'strategy-leadership'],
    value: 'US$6.5m',
    valueUsd: 6_500_000,
    band: 'Under US$10m',
  },
  {
    id: 'mbo-green-building-saas',
    headline:
      'Deal strategy and growth capital for the management buy-out of a green building materials self-certification software business in Europe.',
    corridor: 'Within Europe',
    regions: ['Europe'],
    // The source card prints a "Sector(s):" label with nothing under it, so no
    // sector is asserted here. See FLAG-C2 in content/_source/transactions.md.
    sectors: ['Other'],
    roles: ['MBO and MBI', 'Startups and growth capital', 'Deal strategy'],
    pillars: ['mergers-acquisitions', 'corporate-finance'],
    value: 'US$5m',
    valueUsd: 5_000_000,
    band: 'Under US$10m',
  },
  {
    id: 'working-capital-advertising-partner',
    headline:
      'Working capital finance, performance and management information review, and valuation for the foreign partner of one of the world’s leading advertising groups, in Asia.',
    corridor: 'Within Asia',
    regions: ['Asia'],
    sectors: ['Media & Entertainment'],
    roles: ['Working capital', 'International expansion'],
    pillars: ['corporate-finance', 'strategy-leadership'],
    value: 'US$5m',
    valueUsd: 5_000_000,
    band: 'Under US$10m',
  },
  {
    id: 'debt-label-manufacturer',
    headline: 'Debt and project finance for a leading label manufacturer in Asia.',
    corridor: 'Within Asia',
    regions: ['Asia'],
    sectors: ['Industrial Manufacturing'],
    roles: ['Debt financing', 'Project finance', 'Business strategy'],
    pillars: ['corporate-finance', 'strategy-leadership'],
    value: 'US$5m',
    valueUsd: 5_000_000,
    band: 'Under US$10m',
  },
  {
    id: 'debt-diamond-bullion-merchant',
    headline:
      'Debt financing and business strategy for a leading diamond and bullion merchant in Asia.',
    corridor: 'Within Asia',
    regions: ['Asia'],
    sectors: ['Metals & Mining'],
    roles: ['Debt financing', 'Business strategy', 'Deal strategy'],
    pillars: ['corporate-finance', 'strategy-leadership', 'mergers-acquisitions'],
    value: 'US$5m',
    valueUsd: 5_000_000,
    band: 'Under US$10m',
  },
  {
    id: 'industrial-gases-strategic-sale',
    headline: 'Sell-side advisory on the strategic sale of an industrial gases business in Asia.',
    corridor: 'Within Asia',
    regions: ['Asia'],
    sectors: ['Oil & Gas'],
    roles: ['Sell-side', 'Project finance', 'Deal strategy'],
    pillars: ['mergers-acquisitions', 'corporate-finance'],
    // The old site placed this card between the US$1bn and US$200m deals
    // despite its US$2.5m figure, so either the figure or the placement is
    // wrong. Sorted on the published figure here. See FLAG-C1.
    value: 'US$2.5m',
    valueUsd: 2_500_000,
    band: 'Under US$10m',
  },
] satisfies unknown[];

export const transactions = z.array(Transaction).parse(transactionData);

/**
 * Current mandates, in the source table's order. Every figure, band, industry
 * and region label is the old site's own; only typos and the corrupted
 * apostrophes have been fixed. Currency of these mandates is unconfirmed:
 * the page was static HTML with no date field. See FLAG-L1.
 */
const mandateData = [
  {
    ref: '88',
    dealType: 'Equity Raise',
    amount: 'US$23m',
    band: 'US$10m to US$50m',
    industry: 'Airlines',
    region: 'Africa - Southern',
    description: 'Equity financing for an airline in South Africa',
  },
  {
    ref: '92',
    dealType: 'Equity Raise',
    amount: 'US$7m',
    band: 'US$3m to US$10m',
    industry: 'Consumer Markets & E-Commerce',
    region: 'Asia - South East',
    description: 'Equity financing for the second largest e-commerce firm of a developing nation',
  },
  {
    ref: '21',
    dealType: 'Equity Raise',
    amount: 'US$30m',
    band: 'US$10m to US$50m',
    industry: 'Consumer Markets & E-Commerce',
    region: 'Europe - Western',
    description: 'Business valuation of an e-commerce company',
  },
  {
    ref: '17',
    dealType: 'Distressed Asset Management',
    amount: 'US$100m',
    band: 'US$50m to US$100m',
    industry: 'Dairy',
    region: 'Asia - South East',
    description: 'Distressed asset management and turnaround of a dairy company',
  },
  {
    ref: '95',
    dealType: 'Equity / Debt Raise',
    amount: 'US$220m',
    band: 'Over US$200m',
    industry: 'Energy, Power & Utilities',
    region: 'Asia - South East',
    description:
      'Greenfield geothermal project: development and construction of a 60MW power plant',
  },
  {
    ref: '96',
    dealType: 'Equity / Debt Raise',
    amount: 'US$10m',
    band: 'US$3m to US$10m',
    industry: 'Energy, Power & Utilities',
    region: 'Europe - Western',
    description:
      'UK-based company engaged in the development, manufacture and installation of small wind turbines',
  },
  {
    ref: '71',
    dealType: 'Acquisition',
    amount: 'US$10m',
    band: 'US$3m to US$10m',
    industry: 'Engineering & Construction',
    region: 'Europe - Western',
    description: 'Valuation for a UK-based acquisition of an engineering firm',
  },
  {
    ref: '76',
    dealType: 'Debt Raise',
    amount: 'US$4m',
    band: 'US$3m to US$10m',
    industry: 'Healthcare',
    region: 'Asia - South East',
    description: 'Debt financing for a medical diagnostics company',
  },
  {
    ref: '91',
    dealType: 'IPO Advisory',
    amount: 'US$200m',
    band: 'US$100m to US$200m',
    industry: 'Healthcare',
    region: 'Asia - South East',
    description: 'IPO advisory for a large healthcare services chain',
  },
  {
    ref: '1',
    dealType: 'Equity Raise',
    amount: 'US$50m',
    band: 'US$10m to US$50m',
    industry: 'Healthcare',
    region: 'Asia - South East',
    description: 'Equity financing for a healthcare services chain',
  },
  {
    ref: '50',
    dealType: 'Equity Raise',
    amount: 'US$15m',
    band: 'US$10m to US$50m',
    industry: 'Healthcare',
    region: 'Asia - South East',
    description: 'Fund raise for a medical diagnostics company',
  },
  {
    ref: '33',
    dealType: 'Fund Placement - PE',
    amount: 'US$100m',
    band: 'US$50m to US$100m',
    industry: 'Healthcare',
    region: 'Asia - South East',
    description: 'Fund placement for a healthcare-focused private equity fund',
  },
  {
    ref: '7',
    dealType: 'Equity Raise',
    amount: 'US$30m',
    band: 'US$10m to US$50m',
    industry: 'Healthcare',
    region: 'Europe - Western',
    description: 'Equity financing for a care home in the UK',
  },
  {
    ref: '62',
    dealType: 'Equity Raise',
    amount: 'US$80m',
    band: 'US$50m to US$100m',
    industry: 'Hospitality & Leisure',
    region: 'Asia - South East',
    description: 'Feasibility study and equity raise for India’s largest theme park',
  },
  {
    ref: '68',
    dealType: 'Debt Raise',
    amount: 'US$4m',
    band: 'US$3m to US$10m',
    industry: 'Manufacturing',
    region: 'Asia - South East',
    description: 'Debt financing for a manufacturing company',
  },
  {
    ref: '51',
    dealType: 'Equity Raise',
    amount: 'US$4m',
    band: 'US$3m to US$10m',
    industry: 'Manufacturing',
    region: 'Asia - South East',
    description: 'Equity and debt financing for a manufacturing company',
  },
  {
    ref: '67',
    dealType: 'Divestment',
    amount: 'US$20m',
    band: 'US$10m to US$50m',
    industry: 'Manufacturing',
    region: 'Asia - South East',
    description: 'Divestment of a manufacturing company',
  },
  {
    ref: '90',
    dealType: 'Business Valuation',
    amount: 'US$0.25m',
    band: 'Under US$3m',
    industry: 'Manufacturing',
    region: 'Asia - South East',
    description: 'Business valuation of a food manufacturing company',
  },
  {
    ref: '73',
    dealType: 'Equity Raise',
    amount: 'US$2m',
    band: 'Under US$3m',
    industry: 'Manufacturing',
    region: 'North America',
    description:
      'Equity financing, a joint venture or merger between Chinese and US brands, and market entry of an Italian gelato brand into the US',
  },
  {
    ref: '64',
    dealType: 'Equity Raise',
    amount: 'US$50m',
    band: 'US$10m to US$50m',
    industry: 'Media & Entertainment',
    region: 'Asia - South East',
    description: 'Equity financing for one of the world’s biggest premier futsal leagues',
  },
  {
    ref: '38',
    dealType: 'Equity / Debt Raise',
    amount: 'US$150m',
    band: 'US$100m to US$200m',
    industry: 'Media & Entertainment',
    region: 'Europe - Western',
    description:
      'Equity and debt financing for one of the world’s largest visual effects and special effects houses',
  },
  {
    ref: '46',
    dealType: 'Equity Raise',
    amount: 'US$20m',
    band: 'US$10m to US$50m',
    industry: 'Mining & Metals',
    region: 'Europe - Western',
    description: 'Equity fundraising for a metcoke, nickel and copper mining corporation',
  },
  {
    ref: '93',
    dealType: 'Equity / Debt Raise',
    amount: 'US$30m',
    band: 'US$10m to US$50m',
    industry: 'Mining & Metals',
    region: 'North America',
    description: 'Equity and debt fundraising for a gold and precious metals mining corporation',
  },
  {
    ref: '89',
    dealType: 'Sale',
    amount: 'US$12m',
    band: 'US$10m to US$50m',
    industry: 'Real Estate',
    region: 'Africa - Southern',
    description: 'Sale of a hotel resort in South Africa',
  },
  {
    ref: '77',
    dealType: 'Equity / Debt Raise',
    amount: 'US$75m',
    band: 'US$50m to US$100m',
    industry: 'Real Estate',
    region: 'Asia - South East',
    description: 'Equity and debt financing for a micro-finance business',
  },
  {
    ref: '87',
    dealType: 'Sale',
    amount: 'US$190m',
    band: 'US$100m to US$200m',
    industry: 'Real Estate',
    region: 'Europe - Western',
    description:
      'Equity financing for the acquisition of one of Lake Geneva’s most luxurious hotels',
  },
  {
    ref: '86',
    dealType: 'Sale',
    amount: 'US$36m',
    band: 'US$10m to US$50m',
    industry: 'Real Estate',
    region: 'Europe - Western',
    description:
      'Equity financing for the acquisition of three luxury Swiss hotels for sale, either individually or as a group',
  },
  {
    ref: '83',
    dealType: 'Sale',
    amount: 'US$20m',
    band: 'US$10m to US$50m',
    industry: 'Real Estate',
    region: 'Europe - Western',
    description:
      'Equity financing for the acquisition of three luxury Swiss Alps hotels for sale, either individually or as a group',
  },
  {
    ref: '60',
    dealType: 'Sale',
    amount: 'US$400m',
    band: 'Over US$200m',
    industry: 'Real Estate',
    region: 'Europe - Nordics & Baltics',
    description:
      'Sale of 25 commercial real estate properties in Estonia, either individually or as a group',
  },
  {
    ref: '57',
    dealType: 'Sale',
    amount: 'US$450m',
    band: 'Over US$200m',
    industry: 'Real Estate',
    region: 'North America',
    description: 'Sale of one of the trophy landmarks in the US',
  },
  {
    ref: '18',
    dealType: 'Equity Raise',
    amount: 'US$3m',
    band: 'Under US$3m',
    industry: 'Technology',
    region: 'Europe - Western',
    description:
      'Revenue-generating green building rating system start-up, partnered with the US Green Building Council to market its platform to US manufacturers and distributors',
  },
] satisfies unknown[];

export const mandates = z.array(Mandate).parse(mandateData);
